import { vi as sharedLabels } from '@easy/i18n-common/locales/vi';
import { programVi } from '../features/evaluation-programs/programI18n.ts';
/** Bản dịch tiếng Việt đầy đủ cho Easy Performance. */
import type { I18nDict } from './ko';

export const vi: I18nDict = {
  program: programVi,
  common: {
    action: { create: sharedLabels['common.action.add'], save: sharedLabels['common.action.save'], cancel: sharedLabels['common.action.cancel'], edit: sharedLabels['common.action.edit'], delete: sharedLabels['common.action.delete'], submit: sharedLabels['common.action.submit'], close: sharedLabels['common.action.close'], retry: 'Thử lại' },
    status: { active: sharedLabels['common.status.active'], inactive: sharedLabels['common.status.inactive'], loading: sharedLabels['common.message.loading'], empty: sharedLabels['common.message.no_data'] },
    message: { created: 'Đã tạo thành công.', updated: sharedLabels['common.message.save_success'], deleted: 'Đã xóa thành công.', loadError: sharedLabels['common.message.load_failed'] },
    label: { darkMode: 'Chế độ tối', language: 'Ngôn ngữ', logout: 'Đăng xuất' },
  },
  nav: {
    cockpit: 'Bảng điều hành hiệu suất',
    hr: { cycles: 'Nhân sự > Chu kỳ' },
    kpi: { my: 'KPI của tôi', alignment: 'Liên kết mục tiêu', managerTree: 'Cây KPI (Quản lý)', directorTree: 'Cây KPI (Giám đốc)' },
    review: { self: 'Tự đánh giá', manager: 'Quản lý đánh giá' },
    calibration: { sessions: 'Phiên hiệu chỉnh', director: 'Hiệu chỉnh (Giám đốc)', analytics: 'Phân tích hiệu chỉnh', distribution: 'Mô phỏng phân bổ' },
    report: { hr: 'Nhân sự > Báo cáo', my: 'Kết quả của tôi' },
    admin: { tenants: 'Hệ thống > Khách hàng' },
  },
  workspace: {
    navMy: 'Đánh giá của tôi', navOperate: 'Vận hành đánh giá', appTitle: 'Easy Performance', appSubtitle: 'Từ mục tiêu đến phản hồi', cycle: 'Chu kỳ đánh giá', preparing: 'Đang chuẩn bị không gian vận hành đánh giá.',
    myEvaluation: 'Đánh giá của tôi', operations: 'Vận hành', participants: 'Đối tượng và người đánh giá', participantSelect: 'Đối tượng đánh giá', reviewerSelect: 'Người đánh giá chính', assign: 'Lưu phân công',
    progress: 'Tóm tắt tiến độ', achievements: 'Thành tích', blockers: 'Vướng mắc hoặc hỗ trợ cần thiết', supportNeeded: 'Hỗ trợ cần thiết',
    goal: 'Mục tiêu', goalDescription: 'Tiêu chí thành công hoặc kế hoạch hành động', weight: 'Trọng số (%)', saveDraft: 'Lưu bản nháp', submit: 'Gửi', open: 'Mở đánh giá', next: 'Giai đoạn tiếp theo', publish: 'Công bố kết quả', close: 'Kết thúc đánh giá', acknowledge: 'Xác nhận kết quả',
    setup: 'Thiết lập', participantsPhase: 'Đối tượng đánh giá', goals: 'Thống nhất mục tiêu', checkIn: 'Kiểm tra giữa kỳ', selfReview: 'Tự đánh giá', teamReview: 'Đánh giá nhóm', calibration: 'Hiệu chỉnh', results: 'Kết quả và phản hồi', closure: 'Kết thúc',
    copy: {
      mobileAppTitle: 'Đánh giá hiệu suất', noAssignedCycleTitle: 'Chưa có đánh giá được giao', noAssignedCycleDescription: 'Đánh giá được giao sẽ xuất hiện tại đây khi bộ phận Nhân sự mở đánh giá.', setupDescription: 'Xác nhận thời gian và chính sách vận hành đánh giá.', participantsDescription: 'Phân công đối tượng đánh giá và người đánh giá chính.', goalsDescription: 'Nhân viên lập mục tiêu và quản lý phê duyệt.', checkInDescription: 'Kiểm tra tiến độ và hỗ trợ cần thiết.', selfReviewPhaseDescription: 'Nhân viên tổng hợp thành tích và minh chứng.', teamReviewDescription: 'Người đánh giá chấm các nhân viên được giao.', calibrationDescription: 'Điều chỉnh phân bổ xếp hạng và kết quả đánh giá.', resultsDescription: 'Xem kết quả đã công bố và phản hồi.', closureDescription: 'Xác nhận việc công bố và hoàn tất phản hồi trước khi kết thúc.', currentPhase: 'Giai đoạn hiện tại', noCycleTitle: 'Không có chu kỳ đánh giá đang vận hành', noCycleDescription: 'Hãy tạo chu kỳ đánh giá rồi quản lý đối tượng và các giai đoạn tại đây.', createCycle: 'Tạo chu kỳ đánh giá', loadingMyWork: 'Đang tải công việc đánh giá của tôi.', blockersTitle: 'Hoàn tất các mục sau trước khi chuyển bước', operationDescription: 'Máy chủ quyết định việc chuyển bước dựa trên điều kiện hoàn thành và các mục còn vướng.', calibrationOpen: 'Mở hiệu chỉnh cá nhân', employeeNamePlaceholder: 'Tìm theo tên hoặc mã nhân viên', noParticipantsTitle: 'Chưa phân công đối tượng đánh giá', noParticipantsDescription: 'Hãy phân công nhân viên và người đánh giá chính trước khi mở đánh giá.', member: 'Nhân viên', org: 'Đơn vị', reviewStatus: 'Trạng thái đánh giá', unassigned: 'Chưa phân công', notSpecified: 'Chưa chỉ định', noTask: 'Bạn không có công việc đánh giá trong chu kỳ này.', goalWrite: 'Lập mục tiêu', checkInDescriptionShort: 'Ghi nhận tiến độ mục tiêu và phản hồi, không phải chấm công.', selfReviewDescription: 'Thành tích và kế hoạch phát triển tiếp theo', resultsFeedback: 'Kết quả và phản hồi', notCalculated: 'Chưa tính', acknowledged: 'Bạn đã xác nhận kết quả.', acknowledgeHint: 'Hãy xem kết quả rồi xác nhận đã nhận.', appeal: 'Khiếu nại', appealPlaceholder: 'Mô tả cụ thể lý do cần xem xét.', teamLoading: 'Đang tải nhiệm vụ đánh giá nhóm.', noTeamTitle: 'Chưa có đánh giá nhóm được giao', noTeamDescription: 'Các nhiệm vụ thống nhất mục tiêu, kiểm tra giữa kỳ và đánh giá cuối kỳ sẽ xuất hiện tại đây.', reviewerFeedback: 'Phản hồi giữa kỳ', reviewerFeedbackPlaceholder: 'Nêu định hướng và hỗ trợ cần thiết.', completeCheckIn: 'Hoàn tất kiểm tra giữa kỳ', teamScore: 'Điểm đánh giá nhóm', loadingItems: 'Đang tải hạng mục đánh giá.', reviewComment: 'Nhận xét đánh giá', submitTeamReview: 'Gửi đánh giá nhóm', feedbackSave: 'Lưu phản hồi', feedbackSubmitted: 'Đã lưu phản hồi.',
      statusEmpty: 'Chưa bắt đầu', status_ACTIVE: 'Đang hoạt động', status_EXCLUDED: 'Đã loại trừ', status_DRAFT: 'Bản nháp', status_PENDING_APPROVAL: 'Chờ phê duyệt', status_APPROVED: 'Đã phê duyệt', status_REJECTED: 'Yêu cầu chỉnh sửa', status_EMPLOYEE_SUBMITTED: 'Nhân viên đã gửi', status_MANAGER_COMPLETED: 'Quản lý đã hoàn tất', status_SELF_PENDING: 'Chờ tự đánh giá', status_SELF_SUBMITTED: 'Đã gửi tự đánh giá', status_MANAGER_PENDING: 'Chờ quản lý đánh giá', status_MANAGER_SUBMITTED: 'Quản lý đã gửi đánh giá', status_CALIBRATION: 'Đang hiệu chỉnh', status_FINALIZED: 'Đã chốt', status_PLANNED: 'Đã lên kế hoạch', status_GOAL_SETTING: 'Thiết lập mục tiêu', status_MID_REVIEW: 'Kiểm tra giữa kỳ', status_SELF_REVIEW: 'Tự đánh giá', status_MANAGER_REVIEW: 'Đánh giá nhóm', status_IN_SESSION: 'Đang diễn ra', status_CONFIRMED: 'Đã xác nhận', status_COMPLETED: 'Đã hoàn tất phản hồi', status_ACCEPTED: 'Đã chấp nhận', status_APPEALED: 'Đã khiếu nại', status_RESOLVED: 'Đã xử lý',
      openConfirmTitle: 'Mở đợt đánh giá này?', openConfirmBody: 'Nhân viên sẽ thấy đợt đánh giá và có thể bắt đầu thống nhất mục tiêu.', opened: 'Đã mở đợt đánh giá.', noEmployeeMatches: 'Không tìm thấy nhân viên phù hợp.', advanced: 'Đã chuyển sang giai đoạn tiếp theo.', published: 'Đã công bố kết quả.', closed: 'Đã kết thúc đợt đánh giá.', assigned: 'Đã lưu đối tượng và người đánh giá.', peopleSuffix: ' người', assignmentHint: 'Người đánh giá chính đã chọn sẽ được áp dụng cho các nhân viên được chọn.', reviewerPlaceholder: 'Chọn người đánh giá', loadingParticipants: 'Đang tải đối tượng đánh giá.',
      nextWork: 'Công việc tiếp theo', nextWorkReady: 'Nhiệm vụ tiếp theo đã sẵn sàng.', pendingApprovalSuffix: ' mục chờ phê duyệt', goalCountSuffix: ' mục tiêu', reviewPersonSuffix: ' lượt đánh giá', loadingGoals: 'Đang tải mục tiêu.', noGoals: 'Chưa có mục tiêu nào được gửi.', target: 'Chỉ tiêu', requestRevision: 'Yêu cầu chỉnh sửa', approve: 'Phê duyệt', goalDecisionComment: 'Ý kiến duyệt mục tiêu', goalDecisionPlaceholder: 'Khi yêu cầu chỉnh sửa, cần nêu lý do cụ thể.', goalRejected: 'Đã yêu cầu chỉnh sửa mục tiêu.', goalApproved: 'Đã phê duyệt mục tiêu.', feedbackSaved: 'Đã lưu phản hồi.', checkInCompleted: 'Đã hoàn tất kiểm tra giữa kỳ.', noReviewItems: 'Không có hạng mục đánh giá.', actual: 'Thực tế', autoScore: 'Điểm tự động', managerScore: 'Điểm của quản lý', managerReviewSaved: 'Đã lưu nháp đánh giá của quản lý.', managerReviewSubmitted: 'Đã gửi đánh giá của quản lý.', scoreRequiredHint: 'Hãy nhập điểm cho tất cả hạng mục trước khi gửi.',
      goalEdit: 'Chỉnh sửa mục tiêu', targetValue: 'Giá trị mục tiêu', unit: 'Đơn vị', revisionReason: 'Lý do yêu cầu chỉnh sửa', goalUpdated: 'Đã cập nhật mục tiêu.', saveChanges: 'Lưu thay đổi', goalSubmitted: 'Đã gửi yêu cầu phê duyệt.', requestApproval: 'Yêu cầu phê duyệt', noDescription: 'Không có mô tả', noCheckIns: 'Chưa có bản ghi tiến độ.', asOfDate: 'Ngày ghi nhận', actualValue: 'Giá trị thực tế', progressPercent: 'Tiến độ (%)', note: 'Ghi chú tiến độ', addCheckIn: 'Thêm bản ghi tiến độ', evidenceUrl: 'Liên kết minh chứng', checkInAdded: 'Đã ghi nhận tiến độ.', saveCheckIn: 'Lưu tiến độ', goalCreated: 'Đã lưu mục tiêu.', saveGoal: 'Lưu mục tiêu', checkInSaved: 'Đã lưu nháp kiểm tra giữa kỳ.', checkInSubmitted: 'Đã gửi kiểm tra giữa kỳ.', submitToManager: 'Gửi cho quản lý', selfReviewSaved: 'Đã lưu nháp tự đánh giá.', selfReviewSubmitted: 'Đã gửi tự đánh giá.', finalScore: 'Điểm cuối cùng', finalGrade: 'Xếp hạng', resultAcknowledged: 'Đã xác nhận nhận kết quả.', feedbackFromManager: 'Phản hồi từ quản lý', feedbackAccepted: 'Đã chấp nhận phản hồi.', acceptFeedback: 'Chấp nhận phản hồi', appealSubmitted: 'Đã gửi khiếu nại.', feedbackStatus: 'Trạng thái phản hồi',
      loadingCalibration: 'Đang tải công việc hiệu chỉnh.', distributionTotal: 'Tổng mục tiêu', noCalibrationSession: 'Không có phiên hiệu chỉnh', noCalibrationSessionHint: 'Tạo một phiên cho tất cả đối tượng đang hoạt động.', createCalibrationSession: 'Tạo phiên hiệu chỉnh', calibrationSessionCreated: 'Đã tạo phiên hiệu chỉnh.', calibrationSession: 'Phiên hiệu chỉnh', currentDistribution: 'Phân bổ hiện tại', distributionApplied: 'Đã áp dụng phân bổ mục tiêu.', applyDistribution: 'Áp dụng phân bổ', noCalibrationRows: 'Không có đánh giá nào sẵn sàng để hiệu chỉnh.', reviewSubject: 'Đối tượng đánh giá', adjustedGrade: 'Xếp hạng đã điều chỉnh', adjustmentReason: 'Lý do điều chỉnh', adjustmentSaved: 'Đã lưu xếp hạng và lý do điều chỉnh.', saveAdjustment: 'Lưu điều chỉnh', calibrationConfirmed: 'Đã xác nhận hiệu chỉnh và chốt kết quả', countSuffix: ' đánh giá', confirmCalibration: 'Xác nhận hiệu chỉnh',
      loadingResults: 'Đang tải phân tích kết quả.', resultsAnalysis: 'Phân tích kết quả', finalized: 'Đã chốt', averageScore: 'Điểm trung bình', gradeDistribution: 'Phân bổ xếp hạng', companyWide: 'Toàn công ty', noResultRows: 'Không có dữ liệu kết quả.', loadingFeedback: 'Đang tải nhiệm vụ phản hồi.', feedbackOperations: 'Phản hồi và khiếu nại', appealReason: 'Lý do khiếu nại', feedbackComment: 'Nhận xét phản hồi', feedbackCompleted: 'Đã hoàn tất phản hồi.', completeFeedback: 'Hoàn tất phản hồi', resolution: 'Kết quả xử lý', resolutionUpheld: 'Giữ nguyên kết quả', resolutionAdjustment: 'Cần điều chỉnh', resolutionComment: 'Ghi chú xử lý', appealResolved: 'Đã xử lý khiếu nại.', resolveAppeal: 'Xử lý khiếu nại', noFeedbackAction: 'Không có thao tác nào cho phản hồi này.',
      error_E9804253: 'Tài khoản chưa được liên kết với hồ sơ nhân viên. Hãy yêu cầu bộ phận Nhân sự hoàn tất liên kết.', error_E9804301: 'Bạn không có quyền thực hiện nhiệm vụ đánh giá này.', error_E9804450: 'Không tìm thấy đối tượng đánh giá.', error_E9804451: 'Không tìm thấy người đánh giá được giao.', error_E9804452: 'Chưa có phản hồi được tạo.', error_E9804254: 'Hãy chọn nhân viên và người đánh giá đang hoạt động.', error_E9804935: 'Hoàn tất các yêu cầu được liệt kê trước khi chuyển sang giai đoạn tiếp theo.', error_E9804936: 'Phản hồi này đã hoàn tất và không thể chỉnh sửa.', error_E9804252: 'Không thể công bố kết quả ở giai đoạn hiện tại.', unknownError: 'Không thể xử lý yêu cầu. Vui lòng thử lại.',
    },
  },
  cockpit: {
    title: 'Bảng điều hành hiệu suất', description: 'Theo dõi chu kỳ, tiến độ đánh giá, mức sẵn sàng hiệu chỉnh và công bố báo cáo trên một màn hình.', empty: 'Không có chu kỳ đánh giá đang hoạt động', emptyDescription: 'Tạo chu kỳ để tự động tổng hợp tình trạng đánh giá, hiệu chỉnh và báo cáo.',
    stat: { cycles: 'Chu kỳ', cyclesHint: 'Tình hình vận hành theo các chu kỳ gần đây', reviewProgress: 'Tiến độ đánh giá', reviewProgressHint: '{done}/{total} đánh giá đã gửi hoặc ở giai đoạn sau', calibrationReady: 'Sẵn sàng hiệu chỉnh', calibrationReadyHint: 'Số đánh giá sẵn sàng trong tổng số {total}', reports: 'Báo cáo', reportsHint: 'Đã công bố trên {finalized} đánh giá được chốt' },
    pipeline: { title: 'Quy trình đánh giá', description: 'Phân bổ trạng thái của chu kỳ đã chọn.' },
    distribution: { title: 'Phân bổ xếp hạng', description: 'Hiển thị trực tiếp dữ liệu phản hồi từ API hiệu chỉnh/phân bổ.', current: 'Phân bổ hiện tại', total: 'Tổng cộng {count}', empty: 'Không có dữ liệu phân bổ.' },
    cycles: { title: 'Chu kỳ gần đây', description: 'Xem chu kỳ đang vận hành cùng các trạng thái chu kỳ lân cận.', policy: 'Chính sách' },
  },
  login: {
    personaLabel: 'Dùng thử tài khoản mẫu', personaHint: 'Chọn vai trò để tự động điền tài khoản mẫu trong môi trường đã bật dữ liệu mẫu', tenantCode: 'Mã công ty', tenantCodePlaceholder: 'Mã công ty (không bắt buộc)', emailLabel: sharedLabels['common.label.email'], passwordLabel: 'Mật khẩu', submit: 'Đăng nhập',
    persona: { superAdmin: 'Quản trị hệ thống', hrAdmin: 'Nhân sự', director: 'Giám đốc', manager: 'Quản lý', employee: 'Nhân viên' },
  },
  adminTenants: {
    title: 'Quản lý khách hàng', description: 'Quản trị hệ thống — tạo, khởi tạo, tạm dừng và tiếp tục khách hàng trên mặt phẳng điều khiển', gateOffTitle: 'Đang tắt chế độ đa khách hàng (chế độ một DB)', gateOffBody: 'Mặt phẳng điều khiển chưa được kết nối nên API vòng đời khách hàng trả về 503. Khi bật APP_NEON_MULTITENANCY_ENABLED=true và cấu hình môi trường mặt phẳng điều khiển, màn hình này sẽ tự động hiển thị dữ liệu trực tiếp.', create: 'Tạo khách hàng', empty: 'Chưa có khách hàng', emptyHint: 'Đăng ký khách hàng đầu tiên bằng nút tạo — quá trình khởi tạo Neon sẽ bắt đầu ngay.', createTitle: 'Tạo khách hàng', createHint: 'Thao tác tạo sẽ đăng ký khách hàng trên mặt phẳng điều khiển, kích hoạt gói PERFORMANCE rồi chạy khởi tạo Neon trong nền (mất vài chục giây). Danh sách tự động theo dõi PROVISIONING → ACTIVE.', createFailed: 'Không thể tạo — hãy kiểm tra mã trùng và dữ liệu nhập.',
    field: { code: 'Mã', name: 'Tên', region: 'Khu vực', adminUsername: 'Tên đăng nhập quản trị', adminEmail: 'Email quản trị' },
    column: { code: 'Mã', name: 'Tên', status: 'Trạng thái', region: 'Khu vực', neonProject: 'Dự án Neon', admin: 'Quản trị viên', createdAt: 'Ngày tạo' },
    action: { retry: 'Thử lại', suspend: 'Tạm dừng', resume: 'Tiếp tục', cancel: 'Hủy', create: 'Tạo' },
  },
  cycles: {
    title: 'Chu kỳ đánh giá', create: 'Tạo chu kỳ', empty: 'Chưa có chu kỳ', policy: { notSet: 'Chưa thiết lập chính sách' }, action: { edit: 'Chỉnh sửa', transition: 'Chuyển trạng thái', policy: 'Chỉnh sửa chính sách', delete: 'Xóa' }, field: { name: 'Tên', periodStart: 'Ngày bắt đầu', periodEnd: 'Ngày kết thúc', cycleType: 'Loại chu kỳ', status: 'Trạng thái' },
    type: { HALF_ANNUAL: 'Nửa năm', ANNUAL: 'Hằng năm', QUARTERLY: 'Hằng quý', MONTHLY: 'Hằng tháng', CUSTOM: 'Tùy chỉnh' },
    status: { PLANNED: 'Đã lên kế hoạch', ACTIVE: 'Đang hoạt động', GOAL_SETTING: 'Thiết lập mục tiêu', MID_REVIEW: 'Đánh giá giữa kỳ', SELF_REVIEW: 'Tự đánh giá', MANAGER_REVIEW: 'Quản lý đánh giá', CALIBRATION: 'Hiệu chỉnh', FINALIZED: 'Đã chốt', CANCELLED: 'Đã hủy' },
    operating: { total: 'Chu kỳ', totalHint: 'Các chu kỳ đánh giá đã đăng ký', policyReady: 'Chính sách sẵn sàng', inOperation: 'Đang vận hành', inOperationHint: 'Các chu kỳ chưa chốt hoặc hủy', transitionable: 'Có thể chuyển bước', transitionableHint: 'Chu kỳ có trạng thái tiếp theo khả dụng', policyProgress: 'Mức sẵn sàng của chính sách', timelineTitle: 'Dòng thời gian trạng thái chu kỳ', timelineDescription: 'Xem các chu kỳ đánh giá được phân bổ theo từng giai đoạn vận hành.' },
  },
  policy: {
    title: 'Chính sách đánh giá', field: { distributionMode: 'Chế độ phân bổ', ratingScale: 'Thang xếp hạng', appealEnabled: 'Cho phép khiếu nại', bscEnabled: 'Bật 4 khía cạnh BSC', achievementLogCutoffDays: 'Hạn ghi nhận sau đánh giá (ngày)', forcedDistribution: 'Phân bổ bắt buộc' },
    distributionMode: { HYBRID: 'Kết hợp', FORCED: 'Bắt buộc', ABSOLUTE: 'Tuyệt đối' }, ratingScale: { S_A_B_C_D: 'S/A/B/C/D', ONE_TO_FIVE: '1 đến 5', ONE_TO_HUNDRED: '1 đến 100' }, distributionSum: 'Tổng', distributionSumMustBeOne: 'Tổng tỷ lệ phân bổ phải bằng 1.0 (hiện tại: {sum})',
  },
  kpi: {
    selectCycle: 'Chu kỳ đánh giá', noCycle: 'Chưa có chu kỳ. Hãy tạo chu kỳ trong Nhân sự > Chu kỳ trước.', cyclePlaceholder: 'Chọn chu kỳ',
    level: { CORPORATE: 'Công ty', DIVISION: 'Khối', TEAM: 'Nhóm', INDIVIDUAL: 'Cá nhân' },
    bscPerspective: { FINANCIAL: 'Tài chính', CUSTOMER: 'Khách hàng', INTERNAL_PROCESS: 'Quy trình nội bộ', LEARNING_GROWTH: 'Học hỏi và phát triển', UNASSIGNED: 'Chưa phân loại' },
    source: { MANUAL: 'Nhập thủ công', HCM: 'HCM', EXTERNAL: 'Bên ngoài' },
    weightBadge: { complete: 'Tổng trọng số 100%', incomplete: 'Tổng trọng số {sum}%', exceeded: 'Trọng số vượt quá {sum}%' },
    my: {
      title: 'KPI của tôi', description: 'Xem trọng số, mục tiêu, kết quả mới nhất và tỷ lệ hoàn thành của KPI được giao, đồng thời báo cáo kết quả.', employeeId: 'Mã nhân viên', employeeIdPlaceholder: 'Mã nhân viên (UUID)', load: 'Tải', empty: 'Không có KPI được giao', emptyHint: 'Không có KPI nào được giao cho chu kỳ và nhân viên đã chọn.', needInput: 'Nhập chu kỳ và mã nhân viên rồi tải dữ liệu.',
      col: { node: 'KPI', tree: 'Cây', weight: 'Trọng số', target: 'Mục tiêu', latestActual: 'Kết quả mới nhất', achievementRate: 'Mức hoàn thành' }, reportActual: 'Báo cáo kết quả', actualHistory: 'Lịch sử kết quả',
    },
    alignment: {
      title: 'Liên kết mục tiêu', description: 'So sánh cây KPI của tổ chức với các KPI cá nhân được giao và kết quả thực tế.', tree: 'Cây KPI tổ chức', treePlaceholder: 'Chọn cây để so sánh', needCycle: 'Chọn chu kỳ để tải cây KPI tổ chức.', empty: 'Không có dữ liệu KPI để so sánh', emptyDescription: 'Hãy tạo cây KPI tổ chức hoặc giao KPI cá nhân trước.', treePanel: 'Mục tiêu tổ chức', personalPanel: 'KPI cá nhân được giao', personalPanelDescription: 'Kiểm tra KPI cá nhân có liên kết với cây tổ chức đã chọn hay không.', orgMatch: 'Khớp tổ chức', matched: 'Đã khớp', unmatched: 'Chưa khớp',
      stat: { aligned: 'KPI đã liên kết', alignedHint: 'KPI cá nhân liên kết với cây đã chọn', coverage: 'Tỷ lệ liên kết', coverageHint: 'Dựa trên {tree}', avgAchievement: 'Mức hoàn thành trung bình', avgAchievementHint: 'Trung bình các KPI cá nhân đã có kết quả', unmatched: 'Chưa liên kết', unmatchedHint: 'KPI cá nhân nằm ngoài cây tổ chức đã chọn' },
    },
    manager: { title: 'Cây KPI (Quản lý)', description: 'Xây dựng cây KPI theo chu kỳ đánh giá và quản lý nút cùng phân công.', treeList: 'Danh sách cây KPI', createTree: 'Tạo cây', empty: 'Chu kỳ này chưa có cây KPI', emptyTree: 'Chưa có nút. Hãy thêm nút gốc.', addRootNode: 'Thêm nút gốc', addChild: 'Thêm nút con', editNode: 'Chỉnh sửa nút', deleteNode: 'Xóa nút', manageAssignments: 'Quản lý phân công', editTree: 'Chỉnh sửa cây', deleteTree: 'Xóa cây', childWeightSum: 'Tổng trọng số nút con' },
    director: {
      title: 'Cây KPI (Giám đốc)', description: 'Cây KPI chỉ đọc — có thể bật/tắt nhóm theo 4 khía cạnh BSC.', bscToggle: 'Hiển thị theo 4 khía cạnh BSC', readonly: 'Chỉ đọc', empty: 'Chu kỳ này chưa có cây KPI',
      operating: { trees: 'Cây KPI', treesHint: 'Danh mục KPI tổ chức trong chu kỳ này', bscCoverage: 'Độ phủ BSC', orgScoped: 'Theo đơn vị', orgScopedHint: 'Cây có đơn vị sở hữu', levels: 'Cấp độ', levelsHint: 'Các cấp cây có trong danh mục', bscProgress: 'Tiến độ phủ BSC', nodes: 'Nút KPI', nodesHint: 'Các KPI trong cây đã chọn', bscAssigned: 'Đã gán khía cạnh', weightComplete: 'Đủ trọng số', assignments: 'Phân công', assignmentsHint: 'Tổng lượt giao đối tượng đánh giá trên các nút', weightProgress: 'Tiến độ hoàn tất trọng số' },
    },
    tree: { name: 'Tên cây', level: 'Cấp độ', ownerOrgUnitId: 'Mã đơn vị sở hữu', bscEnabled: 'Bật 4 khía cạnh BSC', create: 'Tạo cây' },
    node: { label: 'Nhãn', weight: 'Trọng số (0–1)', target: 'Mục tiêu', unit: 'Đơn vị', bscPerspective: 'Khía cạnh BSC', source: 'Nguồn', cascadeFromId: 'Mã KPI liên kết cấp trên', parent: 'Nút cha', parentRoot: '(Gốc)', assignments: 'Phân công', assignmentCount: 'Số phân công', create: 'Thêm nút', weightHint: 'Tỷ lệ lớn hơn 0 và không quá 1 (ví dụ: 0.25 = 25%)' },
    assignment: { title: 'Quản lý phân công', employeeId: 'Mã nhân viên', weight: 'Trọng số (ghi đè)', weightOverrideHint: 'Để trống để dùng trọng số mặc định của nút.', targetOverride: 'Mục tiêu ghi đè', add: 'Thêm phân công', empty: 'Chưa có phân công', effectiveWeight: 'Trọng số áp dụng', effectiveTarget: 'Mục tiêu áp dụng' },
    actual: { title: 'Báo cáo kết quả', asOfDate: 'Ngày ghi nhận', actualValue: 'Giá trị thực tế', evidenceUrl: 'URL minh chứng', comment: 'Ghi chú', report: 'Báo cáo kết quả', history: 'Lịch sử kết quả', empty: 'Chưa ghi nhận kết quả', superseded: 'Đã thay thế', latest: 'Mới nhất', correct: 'Điều chỉnh', correctTitle: 'Điều chỉnh kết quả', reportedAt: 'Thời điểm báo cáo' },
    confirmDeleteNode: 'Xóa nút này? Không thể xóa nút có nút con.', confirmDeleteTree: 'Xóa cây này? Tất cả nút, phân công và kết quả trong cây sẽ bị xóa.', confirmDeleteAssignment: 'Xóa phân công này? Các kết quả liên quan cũng sẽ bị xóa.',
  },
  review: {
    status: { DRAFT: 'Bản nháp', SELF_PENDING: 'Chờ tự đánh giá', SELF_SUBMITTED: 'Đã gửi tự đánh giá', MANAGER_PENDING: 'Chờ quản lý đánh giá', MANAGER_SUBMITTED: 'Quản lý đã gửi', CALIBRATION: 'Hiệu chỉnh', FINALIZED: 'Đã chốt', APPEAL_REQUESTED: 'Đã yêu cầu khiếu nại', APPEAL_RESOLVED: 'Đã xử lý khiếu nại', ARCHIVED: 'Đã lưu trữ' },
    field: { kpiScore: 'Điểm KPI', finalScore: 'Điểm cuối cùng', finalGrade: 'Xếp hạng cuối cùng' }, action: { transition: 'Chuyển trạng thái' },
    kpi: { empty: 'Không có hạng mục KPI.', col: { node: 'KPI', weight: 'Trọng số', target: 'Mục tiêu', actual: 'Thực tế', achievementRate: 'Mức hoàn thành', autoScore: 'Điểm tự động', managerScore: 'Điểm của quản lý', itemScore: 'Điểm hạng mục' } },
    self: { title: 'Tự đánh giá', description: 'Xem kết quả tự động của các KPI được giao, sau đó viết và gửi bản tự đánh giá.', employeeId: 'Mã nhân viên', employeeIdPlaceholder: 'Mã nhân viên (UUID)', load: 'Tải', needInput: 'Chọn chu kỳ, nhập mã nhân viên rồi tải dữ liệu.', empty: 'Chưa tạo bản tự đánh giá', emptyHint: 'Bạn có thể bắt đầu tự đánh giá sau khi Nhân sự hoặc quản lý tạo đánh giá.', reviewTitle: 'Tự đánh giá', kpiSection: 'Tự kiểm tra KPI', selfComment: 'Nhận xét tự đánh giá', selfCommentPlaceholder: 'Mô tả thành tích và phần tự đánh giá trong kỳ này.', saveDraft: 'Lưu bản nháp', submit: 'Gửi', submitted: 'Đã gửi bản tự đánh giá.', confirmSubmit: 'Gửi bản tự đánh giá? Sau khi gửi sẽ không thể chỉnh sửa.', lockedHint: 'Chỉ đọc: đã gửi hoặc hiện không ở giai đoạn tự đánh giá.' },
    manager: {
      title: 'Quản lý đánh giá', description: 'Chấm KPI từ danh sách đối tượng theo chu kỳ và so sánh đánh giá của nhân viên với quản lý.', create: 'Tạo đánh giá', needCycle: 'Chọn chu kỳ đánh giá.', empty: 'Chu kỳ này chưa có đánh giá', col: { employeeId: 'Mã nhân viên', status: 'Trạng thái', kpiScore: 'Điểm KPI', finalScore: 'Điểm cuối cùng' }, tabScore: 'Chấm điểm KPI', tabCompare: 'Nhân viên ↔ Quản lý', managerComment: 'Nhận xét của quản lý', managerCommentPlaceholder: 'Viết nhận xét của quản lý về hiệu suất của nhân viên.', saveDraft: 'Lưu bản nháp', submit: 'Gửi', submitted: 'Đã gửi đánh giá của quản lý.', previewKpiScore: 'Xem trước điểm KPI', previewHint: 'Điểm tổng có trọng số được xem trước từ dữ liệu hiện tại. Điểm cuối cùng dùng giá trị của máy chủ sau khi gửi.', notEditableHint: 'Không thể nhập điểm vì đánh giá không ở trạng thái chờ quản lý chấm.',
      workspace: { queue: 'Hàng đợi đánh giá', queueHint: 'Tất cả đối tượng trong chu kỳ hiện tại', managerPending: 'Chờ chấm điểm', managerPendingHint: 'Các đánh giá cần quản lý nhập', submitted: 'Đã gửi hoặc ở giai đoạn sau', avgKpi: 'KPI trung bình', avgKpiHint: 'Dựa trên điểm KPI do máy chủ tính', progress: 'Tiến độ quản lý đánh giá', reviewee: 'Đối tượng đánh giá', revieweeHint: 'Đối tượng đang chọn', serverScoreHint: 'Giá trị do máy chủ tính', noGrade: 'Chưa xếp hạng', finalizedAt: 'Thời điểm chốt', finalized: 'Đã chốt', notFinalized: 'Chưa chốt', scoredItems: 'Hạng mục đã chấm', scoredItemsHint: 'Các KPI có điểm của quản lý', scoringProgress: 'Tiến độ chấm điểm' },
    },
    create: { title: 'Tạo đánh giá', modeSingle: 'Đơn lẻ', modeBulk: 'Hàng loạt', employeeId: 'Mã nhân viên', employeeIdPlaceholder: 'Mã nhân viên (UUID)', employeeIds: 'Các mã nhân viên', employeeIdsHint: 'Phân tách nhiều mã nhân viên bằng dòng mới hoặc dấu phẩy. Đối tượng đã có sẽ tự động được bỏ qua.', employeeIdsPlaceholder: 'uuid-1\nuuid-2\nuuid-3', needEmployeeId: 'Nhập mã nhân viên.', needEmployeeIds: 'Nhập ít nhất một mã nhân viên.', bulkResult: 'Đã tạo {created} / Đã bỏ qua {skipped}', note: 'Đánh giá được tạo ở trạng thái DRAFT.' },
    compare: { self: 'Nhân viên', manager: 'Quản lý', noComment: 'Chưa có nhận xét.', scoreCompare: 'So sánh điểm theo hạng mục', autoScore: 'Điểm tự động', managerScore: 'Điểm của quản lý', delta: 'Chênh lệch' },
  },
  calibration: {
    status: { PLANNED: 'Đã lên kế hoạch', IN_SESSION: 'Đang diễn ra', ADJUSTED: 'Đã điều chỉnh', CONFIRMED: 'Đã xác nhận', CLOSED: 'Đã đóng' }, grade: { UNRATED: 'Chưa xếp hạng' }, action: { transition: 'Chuyển trạng thái', confirm: 'Xác nhận', edit: 'Chỉnh sửa', delete: 'Xóa' },
    page: { title: 'Phiên hiệu chỉnh', description: 'Tạo và vận hành phiên hiệu chỉnh theo chu kỳ, sau đó xác nhận các điều chỉnh xếp hạng.', create: 'Tạo phiên', needCycle: 'Chọn chu kỳ đánh giá.', empty: 'Chu kỳ này chưa có phiên hiệu chỉnh', companyWide: 'Toàn công ty', confirmDelete: 'Xóa phiên này? Chỉ có thể xóa phiên ở trạng thái PLANNED.', col: { status: 'Trạng thái', scheduledAt: 'Lịch dự kiến', ownerOrgUnit: 'Đơn vị phụ trách', participants: 'Người tham gia', adjustments: 'Số điều chỉnh' } },
    form: { createTitle: 'Tạo phiên', editTitle: 'Chỉnh sửa phiên', ownerOrgUnitId: 'Mã đơn vị phụ trách', ownerOrgUnitIdHint: 'Để trống để tạo phiên cho toàn công ty.', ownerOrgUnitIdPlaceholder: 'Mã đơn vị (UUID, không bắt buộc)', scheduledAt: 'Thời gian dự kiến', scheduledAtPlaceholder: 'Thời gian họp hiệu chỉnh dự kiến', participantIds: 'Mã người tham gia', participantIdsHint: 'Nhập mã nhân viên tham gia (UUID) rồi nhấn Enter để thêm.', participantIdsPlaceholder: 'Nhập mã nhân viên rồi nhấn Enter', createNote: 'Phiên được tạo ở trạng thái PLANNED.', editNote: 'Chỉ có thể chỉnh sửa phiên ở trạng thái PLANNED.' },
    confirm: { title: 'Xác nhận phiên', description: 'Xác nhận phiên hiệu chỉnh này? Không thể thay đổi xếp hạng sau khi xác nhận.', finalizeReviews: 'Chốt đánh giá', finalizeReviewsHint: 'Chuyển tất cả đánh giá ở giai đoạn hiệu chỉnh sang FINALIZED. Đánh giá thiếu điểm KPI sẽ được bỏ qua.', finalizeWarning: 'Không thể hoàn tác việc chốt đánh giá. Điểm và xếp hạng sẽ bị khóa sau khi chốt.', resultConfirmed: 'Đã xác nhận phiên.', resultFinalized: 'Đã xác nhận phiên. Đã chốt {finalized} đánh giá / Bỏ qua {skipped}', submit: 'Xác nhận' },
    adjust: { move: 'Chuyển xếp hạng', selectGrade: 'Xếp hạng mục tiêu', title: 'Điều chỉnh xếp hạng', reason: 'Lý do điều chỉnh', reasonPlaceholder: 'Nhập lý do điều chỉnh xếp hạng.', apply: 'Điều chỉnh', done: 'Đã điều chỉnh xếp hạng.' },
    director: { title: 'Hiệu chỉnh dành cho giám đốc', description: 'Xem phân bổ và chọn phiên để điều chỉnh xếp hạng của đối tượng.', needCycle: 'Chọn chu kỳ đánh giá.', selectSession: 'Phiên hiệu chỉnh', sessionPlaceholder: 'Chọn phiên', noSession: 'Chu kỳ này chưa có phiên hiệu chỉnh. Hãy tạo phiên trong phần Nhân sự trước.', notAdjustableHint: 'Chỉ có thể điều chỉnh xếp hạng trong phiên IN_SESSION hoặc ADJUSTED.', reviewsHeading: 'Xếp hạng đối tượng đánh giá', emptyReviews: 'Chu kỳ này chưa có đánh giá', logHeading: 'Lịch sử điều chỉnh', logEmpty: 'Chưa có lịch sử điều chỉnh.', col: { employeeId: 'Mã nhân viên', status: 'Trạng thái', kpiScore: 'Điểm KPI', grade: 'Xếp hạng áp dụng' } },
    analytics: { title: 'Phân tích hiệu chỉnh', description: 'Xem trạng thái phiên, phân bổ xếp hạng và lịch sử điều chỉnh trong một không gian làm việc.', needCycle: 'Chọn chu kỳ đánh giá để xem phân tích hiệu chỉnh.', distributionTitle: 'Phân bổ xếp hạng', distributionDescription: 'So sánh phân bổ hiện tại và mục tiêu.', sessionsTitle: 'Trạng thái phiên', sessionsDescription: 'Các phiên hiệu chỉnh đã đăng ký cho chu kỳ.', timelineTitle: 'Lịch sử điều chỉnh', timelineDescription: 'Nhật ký điều chỉnh xếp hạng của phiên đã chọn.', stat: { sessions: 'Số phiên', sessionsHint: 'Các phiên hiệu chỉnh trong chu kỳ này', ready: 'Sẵn sàng hiệu chỉnh', readyHint: 'Số đánh giá đủ điều kiện trong tổng số {total}', adjustments: 'Số điều chỉnh', adjustmentsHint: 'Tổng mục nhật ký điều chỉnh trong các phiên', forced: 'Phân bổ bắt buộc', forcedHint: 'Trạng thái áp dụng phân bổ' }, timelineCol: { when: 'Thời điểm', employee: 'Nhân viên', grade: 'Thay đổi xếp hạng', reason: 'Lý do' } },
  },
  distribution: {
    bars: { heading: 'Phân bổ xếp hạng', current: 'Hiện tại', target: 'Mục tiêu', totalCount: 'Tổng cộng {count}', targetMarker: 'mục tiêu {ratio}' },
    policy: { mode: 'Chế độ phân bổ', scale: 'Thang xếp hạng', applied: 'Đã áp dụng bắt buộc', notApplied: 'Chưa áp dụng', ready: 'Đủ điều kiện' },
    page: { title: 'Mô phỏng phân bổ', description: 'Mô phỏng phân bổ bắt buộc và áp dụng hàng loạt cho xếp hạng của đối tượng.', needCycle: 'Chọn chu kỳ đánh giá.', notSupported: 'Chính sách hiện tại (chế độ tuyệt đối hoặc thang khác S/A/B/C/D) không hỗ trợ phân bổ bắt buộc.' },
    action: { simulate: 'Mô phỏng', apply: 'Áp dụng bắt buộc' },
    apply: { title: 'Áp dụng phân bổ bắt buộc', warning: 'Áp dụng bắt buộc sẽ thay đổi hàng loạt xếp hạng. Hãy thực hiện cẩn thận.', confirmText: 'Thay đổi xếp hạng của {count} đối tượng để khớp phân bổ mục tiêu. Tiếp tục?', result: 'Đã áp dụng {applied} / Bỏ qua {skipped}' },
    proposed: { heading: 'Kết quả mô phỏng', empty: 'Không có đối tượng cho phân bổ bắt buộc (không có đánh giá sẵn sàng hiệu chỉnh và có điểm KPI).', changed: 'Đã thay đổi', col: { employeeId: 'Mã nhân viên', kpiScore: 'Điểm KPI', currentGrade: 'Xếp hạng hiện tại', proposedGrade: 'Xếp hạng đề xuất' } },
    log: { heading: 'Lịch sử áp dụng', applied: 'Đã áp dụng {count}', skipped: 'Đã bỏ qua {count}' },
  },
  report: {
    hr: {
      title: 'Báo cáo', description: 'Công bố hàng loạt báo cáo kết quả cho các đánh giá đã chốt và theo dõi trạng thái xem/xác nhận.', needCycle: 'Chọn chu kỳ đánh giá.', needFinalized: 'Chỉ có thể công bố báo cáo khi chu kỳ ở trạng thái FINALIZED.', summaryFinalized: 'Đánh giá đã chốt', summaryPublished: 'Đã công bố', publish: 'Công bố tất cả', publishTitle: 'Công bố báo cáo hàng loạt', publishConfirm: 'Công bố báo cáo cho các đối tượng chưa được công bố trong {count} đánh giá đã chốt. Tiếp tục?', publishResult: 'Đã công bố {published} / Bỏ qua {skipped}', empty: 'Chưa công bố báo cáo', emptyHint: 'Sau khi chốt chu kỳ, hãy công bố hàng loạt để tạo báo cáo.', viewed: 'Đã xem', notViewed: 'Chưa xem', acknowledged: 'Đã xác nhận', notAcknowledged: 'Chưa xác nhận', superseded: 'Đã công bố lại', supersede: 'Công bố lại', supersedeTitle: 'Công bố lại báo cáo', supersedeWarning: 'Công bố lại sẽ tạo báo cáo mới, đóng băng lại theo các giá trị đã chốt và phân bổ mới nhất. Báo cáo hiện tại vẫn được lưu làm lịch sử.', supersedeDone: 'Đã công bố lại báo cáo.',
      governance: { title: 'Quản trị báo cáo', description: 'Theo dõi mức sẵn sàng công bố, lượt xem, xác nhận và lịch sử công bố lại trên một màn hình.', readiness: 'Sẵn sàng công bố', readinessHint: 'Dựa trên {count} đánh giá đã chốt', published: 'Báo cáo đang có hiệu lực', viewed: 'Tỷ lệ xem', acknowledged: 'Tỷ lệ xác nhận', superseded: 'Báo cáo lịch sử', progressPublished: 'Tiến độ công bố', progressViewed: 'Tiến độ xem', progressAcknowledged: 'Tiến độ xác nhận', listTitle: 'Báo cáo đang có hiệu lực', listDescription: 'Các báo cáo mới nhất hiện có hiệu lực đối với nhân viên.', historyTitle: 'Lịch sử công bố lại', historyDescription: 'Các báo cáo cũ bị thay thế khi công bố lại được lưu để kiểm toán.', historyEmpty: 'Chưa có lịch sử công bố lại' },
      col: { employeeId: 'Mã nhân viên', finalGrade: 'Xếp hạng cuối cùng', publishedAt: 'Thời điểm công bố', status: 'Trạng thái' },
    },
    my: { title: 'Kết quả của tôi', description: 'Xem báo cáo kết quả đã chốt và xác nhận đã nhận.', employeeId: 'Mã nhân viên', employeeIdPlaceholder: 'Mã nhân viên (UUID)', load: 'Tải', needInput: 'Nhập chu kỳ và mã nhân viên rồi tải dữ liệu.', empty: 'Báo cáo chưa được công bố', emptyHint: 'Bạn có thể xem báo cáo tại đây sau khi Nhân sự công bố kết quả.', acknowledgeDone: 'Đã xác nhận kết quả.' },
    card: { finalGrade: 'Xếp hạng cuối cùng', finalScore: 'Điểm cuối cùng', kpiScore: 'Điểm KPI', mboScore: 'Điểm MBO', competencyScore: 'Điểm năng lực', mraScore: 'Điểm đánh giá đa chiều', scoreP1: 'Sắp có', kpiSection: 'Tóm tắt hạng mục KPI', managerComment: 'Nhận xét của quản lý', noComment: 'Không có nhận xét.', distributionHeading: 'Phân bổ xếp hạng toàn công ty', distributionHint: 'Phân bổ tỷ lệ xếp hạng đã chốt của toàn công ty tại thời điểm công bố. Xếp hạng của bạn được đánh dấu.', distributionEmpty: 'Không có dữ liệu phân bổ.', distributionMine: 'Xếp hạng của tôi', acknowledgeHeading: 'Xác nhận kết quả', acknowledgeHint: 'Ghi nhận rằng bạn đã xem kết quả. Sau khi xác nhận sẽ không thể thay đổi.', acknowledge: 'Xác nhận', acknowledgedButton: 'Đã xác nhận', acknowledged: 'Đã xác nhận' },
    packet: { title: 'Hồ sơ kết quả', description: 'Xem xếp hạng cuối cùng, điểm và trạng thái vòng đời đã được đóng băng tại thời điểm công bố.', publishedAt: 'Đã công bố {date}', kpiItems: '{count} hạng mục KPI', viewStatus: 'Trạng thái xem', viewed: 'Đã xem', notViewed: 'Đang ghi nhận lượt xem', ackStatus: 'Trạng thái xác nhận', acknowledged: 'Đã xác nhận', notAcknowledged: 'Cần xác nhận', lifecyclePending: 'Chưa được ghi nhận', scoreTitle: 'Chi tiết điểm', scoreDescription: 'Các khía cạnh hiệu suất chỉ đọc được tính vào điểm cuối cùng.', kpiDescription: 'Ảnh chụp các hạng mục KPI trong báo cáo đã chốt.', commentDescription: 'Nhận xét của quản lý được đóng băng khi báo cáo được chốt.', developmentTitle: 'Hành động phát triển', developmentDescription: 'Theo dõi nhiệm vụ phát triển và lần kiểm tra tiếp theo sau kết quả.', developmentEmpty: 'Chưa có hành động phát triển', developmentEmptyDescription: 'Mục tiêu phát triển, phản hồi cố vấn và đề xuất học tập sẽ xuất hiện tại đây khi được kết nối.' },
  },
  domain: {
    app: { title: 'easy-performance-management', subtitle: 'Quản lý hiệu suất' },
    nav: { section: 'Hiệu suất', selfEvaluation: 'Tự đánh giá', personalOkr: 'OKR cá nhân', reflectionJournal: 'Nhật ký nhìn lại', mentorFeedback: 'Phản hồi cố vấn' },
    selfEvaluation: { title: 'Tự đánh giá', description: 'Lập bản nháp và gửi tự đánh giá theo quý / năm', empty: 'Chưa có bản tự đánh giá', emptyDescription: 'Tạo bản tự đánh giá mới để bắt đầu chu kỳ quý.', period: 'Kỳ', content: 'Nội dung', score: 'Điểm tự đánh giá', status: 'Trạng thái', statusDraft: 'Bản nháp', statusSubmitted: 'Đã gửi', statusReviewed: 'Đã xem xét', statusFinalized: 'Đã chốt' },
    personalOkr: { title: 'OKR cá nhân', description: 'Mục tiêu và kết quả then chốt theo quý (OKR)', empty: 'Chưa có OKR', emptyDescription: 'Thêm OKR vào đầu quý để theo dõi mục tiêu cá nhân.', objective: 'Mục tiêu', progress: 'Tiến độ', period: 'Kỳ', status: 'Trạng thái', statusActive: 'Đang hoạt động', statusAtRisk: 'Có rủi ro', statusCompleted: 'Đã hoàn thành', statusArchived: 'Đã lưu trữ' },
    reflectionJournal: { title: 'Nhật ký nhìn lại', description: 'Nhật ký nhìn lại theo phương pháp KPT / 4Ls / SSC', empty: 'Chưa có nội dung nhìn lại', emptyDescription: 'Chọn một phương pháp để viết nội dung nhìn lại đầu tiên.', reflectionDate: 'Ngày nhìn lại', method: 'Phương pháp', content: 'Nội dung', isPrivate: 'Riêng tư', methodKpt: 'KPT (Duy trì/Vấn đề/Thử nghiệm)', methodFourLs: '4Ls (Yêu thích/Học được/Thiếu sót/Mong muốn)', methodSsc: 'SSC (Dừng lại/Bắt đầu/Tiếp tục)' },
    mentorFeedback: { title: 'Phản hồi cố vấn', description: 'Phản hồi 1:1 giữa quản lý và nhân viên (Phát triển / Ghi nhận / Huấn luyện / Trao đổi)', empty: 'Chưa có phản hồi', emptyDescription: 'Ghi lại phản hồi 1:1 đầu tiên để hỗ trợ sự phát triển của nhóm.', feedbackDate: 'Ngày phản hồi', mentor: 'Người cố vấn', mentee: 'Người được cố vấn', category: 'Phân loại', content: 'Nội dung', acknowledged: 'Đã xác nhận', categoryGrowth: 'Phát triển / Học hỏi', categoryRecognition: 'Ghi nhận / Điểm mạnh', categoryCoaching: 'Huấn luyện / Cải thiện', categoryConversation: 'Trao đổi 1:1' },
  },
  error: {
    boundary: 'Lỗi hiển thị trang', unknown: 'Đã xảy ra lỗi không xác định.', network: 'Đã xảy ra lỗi mạng.', unauthorized: 'Cần đăng nhập.', forbidden: 'Bạn không có quyền truy cập.',
    E9804441: 'Không tìm thấy chu kỳ', E9804231: 'Chuyển trạng thái không hợp lệ', E9804921: 'Đã tồn tại chu kỳ trùng tên', E9804232: 'Khoảng thời gian không hợp lệ (ngày kết thúc phải sau ngày bắt đầu)', E9804922: 'Không thể xóa chu kỳ ở trạng thái ACTIVE hoặc giai đoạn sau', E9804442: 'Không tìm thấy chính sách', E9804233: 'Tổng tỷ lệ phân bổ phải bằng 1.0', E9804234: 'Các khóa phân bổ không khớp với thang xếp hạng', E9804235: 'Chế độ FORCED yêu cầu thiết lập phân bổ', E9804923: 'Không thể thay đổi chế độ phân bổ hoặc thang xếp hạng sau khi kích hoạt chu kỳ', E9804443: 'Không tìm thấy cây KPI', E9804444: 'Không tìm thấy nút KPI', E9804445: 'Không tìm thấy phân công KPI', E9804446: 'Không tìm thấy kết quả KPI', E9804236: 'Nút cha thuộc một cây khác', E9804237: 'Trọng số phải lớn hơn 0 và không quá 1', E9804238: 'Tổng trọng số các nút cùng cấp vượt quá 1.0', E9804239: 'P0 chỉ hỗ trợ nguồn MANUAL', E9804924: 'Nhân viên này đã được giao cho nút này', E9804925: 'Không thể điều chỉnh lại kết quả đã bị thay thế', E9804926: 'Không thể xóa nút có nút con', E9804927: 'Không thể thay đổi KPI trong chu kỳ đã chốt hoặc hủy', E9804447: 'Không tìm thấy đánh giá', E9804240: 'Chuyển trạng thái không hợp lệ', E9804241: 'Không thể chuyển trạng thái ở giai đoạn hiện tại của chu kỳ', E9804242: 'Điểm của quản lý phải từ 0 đến 100', E9804243: 'Có phân công KPI không thuộc đánh giá này', E9804244: 'Không thể chốt vì thiếu điểm KPI', E9804245: 'Không thể chỉnh sửa phần này ở trạng thái hiện tại', E9804928: 'Đã tồn tại đánh giá cho cùng đối tượng', E9804929: 'Không thể chỉnh sửa đánh giá đã gửi hoặc đóng', E9804930: 'Chỉ có thể xóa đánh giá ở trạng thái DRAFT', E9804448: 'Không tìm thấy phiên hiệu chỉnh', E9804246: 'Chuyển trạng thái phiên không hợp lệ (chỉ được xác nhận bằng thao tác xác nhận)', E9804247: 'Phân bổ mục tiêu không hợp lệ (khóa S/A/B/C/D, tổng 1.0, không có giá trị âm)', E9804248: 'Phân bổ bắt buộc chỉ khả dụng ở chế độ FORCED/HYBRID', E9804249: 'Phân bổ bắt buộc chỉ hỗ trợ thang S/A/B/C/D', E9804250: 'Không thể thực hiện thao tác này ở giai đoạn hiện tại (yêu cầu giai đoạn CALIBRATION)', E9804251: 'Điều chỉnh xếp hạng không hợp lệ (kiểm tra xếp hạng hoặc đánh giá mục tiêu)', E9804931: 'Không thể chỉnh sửa, điều chỉnh hoặc xác nhận phiên đã xác nhận/đóng', E9804932: 'Chỉ có thể xóa phiên ở trạng thái PLANNED', E9804933: 'Chỉ có thể điều chỉnh đánh giá ở giai đoạn hiệu chỉnh', E9804449: 'Không tìm thấy báo cáo', E9804252: 'Chỉ có thể công bố báo cáo khi chu kỳ ở trạng thái FINALIZED', E9804934: 'Không thể xem, xác nhận hoặc công bố lại báo cáo cũ đã bị thay thế',
    E9804453: 'Không tìm thấy chương trình đánh giá.', E9804454: 'Không tìm thấy đối tượng đánh giá.', E9804455: 'Không tìm thấy mục tiêu đánh giá.', E9804456: 'Không tìm thấy nội dung đánh giá đã gửi.', E9804457: 'Không tìm thấy điều chỉnh điểm.', E9804458: 'Không tìm thấy phản hồi đánh giá.', E9804302: 'Bạn không có quyền sử dụng chương trình đánh giá này.', E9804256: 'Hãy kiểm tra thiết lập chương trình đánh giá.', E9804257: 'Không thể thực hiện thao tác này ở giai đoạn hiện tại.', E9804258: 'Loại đánh giá này hiện chưa được hỗ trợ.', E9804937: 'Không thể đổi thiết lập của đánh giá đang tiến hành hoặc đã hoàn tất.', E9804938: 'Hãy hoàn tất công việc đánh giá bắt buộc trước khi tiếp tục.', E9804939: 'Chương trình hoặc phân công đánh giá này đã tồn tại.', E9804940: 'Kết quả đánh giá chưa được công bố.', E9804460: 'Không tìm thấy tài liệu đánh giá được yêu cầu.', E9804360: 'Bạn không có quyền sử dụng tài liệu đánh giá này.', E9804260: 'Hãy kiểm tra nội dung đã nhập cho tài liệu đánh giá.', E9804960: 'Đã tồn tại tài liệu đánh giá trùng hoặc xung đột.', E9804961: 'Không thể thay đổi tài liệu đánh giá đã hoàn tất hoặc bị khóa.', E9804261: 'Tệp đính kèm phải có dung lượng không quá 20 MB.', E9804262: 'Định dạng tệp đính kèm này không được hỗ trợ.',
  },
  validation: { email: 'Hãy nhập địa chỉ email hợp lệ.', password: 'Hãy nhập mật khẩu.' },
  blockers: {
    MISSING_EMPLOYEE_BINDING: 'Cần liên kết tài khoản với hồ sơ nhân viên.', NO_ACTIVE_PARTICIPANTS: 'Hãy phân công đối tượng đánh giá.', PARTICIPANT_NOT_ACTIVE: 'Cần có đối tượng đánh giá đang hoạt động.', MISSING_MANAGER: 'Hãy phân công người đánh giá chính.', GOAL_MISSING: 'Hãy tạo mục tiêu đánh giá.', GOAL_NOT_APPROVED: 'Hãy kiểm tra chính sách đánh giá và trạng thái phê duyệt mục tiêu.', GOAL_ACTUAL_MISSING: 'Hãy ghi nhận kết quả thực tế của mục tiêu.', MID_REVIEW_INCOMPLETE: 'Hãy hoàn tất kiểm tra giữa kỳ.', SELF_REVIEW_INCOMPLETE: 'Hãy gửi bản tự đánh giá.', MANAGER_REVIEW_INCOMPLETE: 'Hãy gửi đánh giá nhóm.', CALIBRATION_INCOMPLETE: 'Hãy xác nhận hiệu chỉnh xếp hạng.', REPORT_NOT_PUBLISHED: 'Hãy công bố kết quả.', REPORT_NOT_ACKNOWLEDGED: 'Nhân viên cần xác nhận kết quả của mình.', FEEDBACK_INCOMPLETE: 'Hãy hoàn tất phản hồi và xử lý khiếu nại.',
  },
};
