package com.easyperformance.program;

import com.easyperformance.program.ProgramDtos.*;
import com.easyperformance.program.ProgramTypes.*;
import com.easyperformance.workflow.ActorAccess.Actor;
import com.easyware.platform.error.ApiException;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;
import java.util.*;

@Service
public class EvaluationProgramService {
 private final EvaluationProgramRepository programs;private final EvaluationProgramRevisionRepository revisions;private final ProgramParticipantRepository participants;private final ProgramReviewerAssignmentRepository reviewers;private final ProgramAccess access;private final ProgramJson json;private final ProgramAuditService audit;
 public EvaluationProgramService(EvaluationProgramRepository programs,EvaluationProgramRevisionRepository revisions,ProgramParticipantRepository participants,ProgramReviewerAssignmentRepository reviewers,ProgramAccess access,ProgramJson json,ProgramAuditService audit){this.programs=programs;this.revisions=revisions;this.participants=participants;this.reviewers=reviewers;this.access=access;this.json=json;this.audit=audit;}

 @Transactional public ProgramResponse create(Actor actor,ProgramCreateRequest request){access.requireOperator(actor);validateDates(request.startsOn(),request.endsOn(),request.asOfDate());validateKind(request.kind());if(programs.existsByTenantIdAndEvaluationYearAndName(actor.tenantId(),request.evaluationYear(),request.name().trim()))throw new ApiException(ProgramErrorCode.PROGRAM_DUPLICATE);ProgramConfiguration config=ProgramConfigurationFactory.defaults(request.kind());EvaluationProgram p=new EvaluationProgram();p.setTenantId(actor.tenantId());p.setName(request.name().trim());p.setEvaluationYear(request.evaluationYear());p.setAsOfDate(request.asOfDate());p.setStartsOn(request.startsOn());p.setEndsOn(request.endsOn());p.setKind(request.kind());p.setDefinitionJson(json.write(config));try{p=programs.save(p);}catch(DataIntegrityViolationException e){throw new ApiException(ProgramErrorCode.PROGRAM_DUPLICATE);}revision(actor,p,"initial definition");audit.record(actor,p.getId(),null,ProgramEventType.PROGRAM_CREATED,"program created",Map.of("name",p.getName()));return response(p);}
 @Transactional(readOnly=true) public Page<ProgramSummaryResponse> list(Actor actor,Pageable pageable){if(access.operator(actor))return programs.findAllByTenantIdOrderByEvaluationYearDescCreatedAtDesc(actor.tenantId(),pageable).map(this::summary);if(actor.employeeId()==null)return Page.empty(pageable);Set<UUID> ids=new LinkedHashSet<>();participants.findAllByTenantIdAndEmployeeIdAndStatusOrderByCreatedAtDesc(actor.tenantId(),actor.employeeId(),ParticipantStatus.ACTIVE).forEach(p->ids.add(p.getProgramId()));reviewers.findAllByTenantIdAndReviewerEmployeeIdAndStatusNot(actor.tenantId(),actor.employeeId(),AssignmentStatus.REVOKED).forEach(r->ids.add(r.getProgramId()));List<ProgramSummaryResponse> rows=ids.stream().map(id->programs.findByIdAndTenantId(id,actor.tenantId()).orElse(null)).filter(Objects::nonNull).filter(p->p.getStatus()!=ProgramStatus.DRAFT).sorted(Comparator.comparing(EvaluationProgram::getEvaluationYear).reversed().thenComparing(EvaluationProgram::getName)).map(this::summary).toList();int from=Math.min((int)pageable.getOffset(),rows.size());int to=Math.min(from+pageable.getPageSize(),rows.size());return new PageImpl<>(rows.subList(from,to),pageable,rows.size());}
 @Transactional(readOnly=true) public ProgramResponse get(Actor actor,UUID id){access.requireOperator(actor);return response(access.program(actor,id));}
 @Transactional public ProgramResponse updateBasic(Actor actor,UUID id,ProgramBasicUpdateRequest request){EvaluationProgram p=access.lockedProgram(actor,id);requireDraft(p);validateDates(request.startsOn(),request.endsOn(),request.asOfDate());String name=request.name().trim();if(programs.existsByTenantIdAndEvaluationYearAndNameAndIdNot(actor.tenantId(),request.evaluationYear(),name,id))throw new ApiException(ProgramErrorCode.PROGRAM_DUPLICATE);p.setName(name);p.setEvaluationYear(request.evaluationYear());p.setAsOfDate(request.asOfDate());p.setStartsOn(request.startsOn());p.setEndsOn(request.endsOn());programs.save(p);audit.record(actor,id,null,ProgramEventType.PROGRAM_BASIC_UPDATED,"program basic information updated",Map.of("evaluationYear",request.evaluationYear()));return response(p);}
 @Transactional public ProgramResponse updateDefinition(Actor actor,UUID id,DefinitionUpdateRequest request){EvaluationProgram p=access.lockedProgram(actor,id);requireDraft(p);ProgramConfiguration normalized=ProgramConfigurationFactory.normalize(request.configuration());validateConfiguration(p,normalized);p.setDefinitionJson(json.write(normalized));p.setDefinitionRevision(p.getDefinitionRevision()+1);programs.save(p);revision(actor,p,request.revisionReason());audit.record(actor,id,null,ProgramEventType.DEFINITION_REVISED,request.revisionReason(),Map.of("revision",p.getDefinitionRevision()));return response(p);}
 @Transactional public ProgramResponse copy(Actor actor,UUID sourceId,ProgramCopyRequest request){access.requireOperator(actor);EvaluationProgram source=programs.findByIdAndTenantId(sourceId,actor.tenantId()).orElseThrow(()->new ApiException(ProgramErrorCode.PROGRAM_NOT_FOUND));return createFromCopy(actor,source,request);}
 private ProgramResponse createFromCopy(Actor actor,EvaluationProgram source,ProgramCopyRequest request){validateDates(request.startsOn(),request.endsOn(),request.asOfDate());if(programs.existsByTenantIdAndEvaluationYearAndName(actor.tenantId(),request.evaluationYear(),request.name().trim()))throw new ApiException(ProgramErrorCode.PROGRAM_DUPLICATE);EvaluationProgram p=new EvaluationProgram();p.setTenantId(actor.tenantId());p.setName(request.name().trim());p.setEvaluationYear(request.evaluationYear());p.setAsOfDate(request.asOfDate());p.setStartsOn(request.startsOn());p.setEndsOn(request.endsOn());p.setKind(source.getKind());p.setDefinitionJson(source.getDefinitionJson());p=programs.save(p);revision(actor,p,"copied from "+source.getId());audit.record(actor,p.getId(),null,ProgramEventType.PROGRAM_CREATED,"program copied",Map.of("sourceProgramId",source.getId()));return response(p);}
 @Transactional(readOnly=true) public List<DefinitionRevisionResponse> revisions(Actor actor,UUID id){access.requireOperator(actor);access.program(actor,id);return revisions.findAllByTenantIdAndProgramIdOrderByRevisionDesc(actor.tenantId(),id).stream().map(r->new DefinitionRevisionResponse(r.getId(),r.getProgramId(),r.getRevision(),r.getReason(),json.configuration(r.getDefinitionJson()),r.getActorEmployeeId(),r.getCreatedAt())).toList();}
 @Transactional public ProgramResponse applyCommonItems(Actor actor,UUID id){EvaluationProgram p=access.lockedProgram(actor,id);if(p.getStatus()==ProgramStatus.FINALIZED||p.getStatus()==ProgramStatus.CANCELLED)throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED);p.setAppliedItemRevision(p.getDefinitionRevision());programs.save(p);audit.record(actor,id,null,ProgramEventType.DEFINITION_REVISED,"common items applied",Map.of("revision",p.getAppliedItemRevision()));return response(p);}
 @Transactional public ProgramResponse open(Actor actor,UUID id){EvaluationProgram p=access.lockedProgram(actor,id);requireDraft(p);ProgramConfiguration c=json.configuration(p.getDefinitionJson());validateConfiguration(p,c);if(p.getAppliedItemRevision()!=p.getDefinitionRevision())throw new ApiException(ProgramErrorCode.PROGRAM_INCOMPLETE,Map.of("reason","COMMON_ITEMS_NOT_APPLIED"));p.setStatus(ProgramStatus.OPEN);p.setOpenedAt(Instant.now());programs.save(p);audit.record(actor,id,null,ProgramEventType.OPENED,"program opened",Map.of());return response(p);}
 ProgramResponse response(EvaluationProgram p){return new ProgramResponse(p.getId(),p.getTenantId(),p.getName(),p.getEvaluationYear(),p.getKind(),p.getStatus(),p.getAsOfDate(),p.getStartsOn(),p.getEndsOn(),p.getDefinitionRevision(),json.configuration(p.getDefinitionJson()),p.getOpenedAt(),p.getFinalizedAt(),p.getCreatedAt(),p.getUpdatedAt());}
 MemberProgramOverview memberOverview(EvaluationProgram p){ProgramConfiguration c=json.configuration(p.getDefinitionJson());ScaleDefinitionInput scale=c.scales().stream().filter(s->s.id().equals(c.calculation().inputScaleId())).findFirst().orElseThrow(()->new ProgramRuleViolation("INPUT_SCALE","input scale is missing"));PublicationPolicyInput policy=c.publication();return new MemberProgramOverview(p.getId(),p.getName(),p.getEvaluationYear(),p.getKind(),p.getStatus(),p.getAsOfDate(),p.getStartsOn(),p.getEndsOn(),c.goalMode(),c.stages().stream().filter(StageDefinitionInput::enabled).map(s->new MemberStageOverview(s.stage(),s.startsOn(),s.endsOn())).toList(),new MemberScaleOverview(scale.name(),scale.kind(),scale.levels().stream().map(l->new MemberScaleLevel(l.code(),l.label(),l.color())).toList()),policy.previousRoundVisibility(),policy.showReviewerAllocation(),policy.memberResultVisibility(),policy.feedbackEnabled(),policy.appealEnabled());}
 ProgramSummaryResponse summary(EvaluationProgram p){return new ProgramSummaryResponse(p.getId(),p.getName(),p.getEvaluationYear(),p.getKind(),p.getStatus(),p.getAsOfDate(),p.getStartsOn(),p.getEndsOn(),p.getDefinitionRevision(),participants.countByTenantIdAndProgramId(p.getTenantId(),p.getId()),p.getCreatedAt(),p.getUpdatedAt());}
 private void revision(Actor a,EvaluationProgram p,String reason){EvaluationProgramRevision r=new EvaluationProgramRevision();r.setTenantId(a.tenantId());r.setProgramId(p.getId());r.setRevision(p.getDefinitionRevision());r.setReason(reason);r.setDefinitionJson(p.getDefinitionJson());r.setActorEmployeeId(a.employeeId());revisions.save(r);}
 private void requireDraft(EvaluationProgram p){if(p.getStatus()!=ProgramStatus.DRAFT)throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED,Map.of("status",p.getStatus()));}
 private void validateKind(EvaluationKind kind){if(kind==EvaluationKind.MULTI_RATER||kind==EvaluationKind.COMBINED)throw new ApiException(ProgramErrorCode.PROGRAM_TYPE_UNSUPPORTED,Map.of("supported",List.of(EvaluationKind.PERFORMANCE,EvaluationKind.COMPETENCY)));}
 private void validateDates(java.time.LocalDate start,java.time.LocalDate end,java.time.LocalDate asOf){if(end.isBefore(start)||asOf.isAfter(end))throw new ApiException(ProgramErrorCode.PROGRAM_INVALID,Map.of("reason","INVALID_DATES"));}
 private void validateConfiguration(EvaluationProgram p,ProgramConfiguration c){ProgramDefinitionValidator.validate(c);Set<UUID> scales=new HashSet<>();c.scales().forEach(s->{if(!scales.add(s.id()))throw new ProgramRuleViolation("DUPLICATE_SCALE","scale ids must be unique");});if(!scales.contains(c.calculation().inputScaleId())||!scales.contains(c.calculation().resultScaleId()))throw new ProgramRuleViolation("SCALE_REFERENCE","calculation scales must exist");Set<UUID> groups=new HashSet<>();c.groups().forEach(g->{if(!groups.add(g.id()))throw new ProgramRuleViolation("DUPLICATE_GROUP","group ids must be unique");});c.commonItems().forEach(i->{if(!groups.contains(i.groupId())||!scales.contains(i.scaleId()))throw new ProgramRuleViolation("ITEM_REFERENCE","common item group and scale must exist");if(i.round()<0||i.round()>3)throw new ProgramRuleViolation("ITEM_ROUND","common item round must be 0..3");});c.stages().forEach(s->{if(s.enabled()&&s.startsOn()!=null&&s.endsOn()!=null&&(s.endsOn().isBefore(s.startsOn())||s.startsOn().isBefore(p.getStartsOn())||s.endsOn().isAfter(p.getEndsOn())))throw new ProgramRuleViolation("STAGE_DATES","stage dates must be ordered and inside the program period");});}
}
