package com.easyperformance.program;
import com.easyperformance.program.ProgramDtos.GuideAttachmentResponse;import com.easyperformance.program.ProgramTypes.ProgramStatus;import com.easyperformance.workflow.ActorAccess.Actor;import com.easyware.platform.error.ApiException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service
public class ProgramGuideService{
 public static final int MAX_BYTES=10*1024*1024;private static final Set<String> TYPES=Set.of("application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","text/plain");private final ProgramGuideAttachmentRepository files;private final ProgramAccess access;
 public ProgramGuideService(ProgramGuideAttachmentRepository files,ProgramAccess access){this.files=files;this.access=access;}
 @Transactional public GuideAttachmentResponse upload(Actor actor,UUID programId,String filename,String contentType,byte[] bytes){access.requireOperator(actor);EvaluationProgram p=access.program(actor,programId);if(p.getStatus()!=ProgramStatus.DRAFT)throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED);if(bytes==null||bytes.length==0||bytes.length>MAX_BYTES||!TYPES.contains(contentType)||!validMagic(contentType,bytes))throw new ProgramRuleViolation("GUIDE_FILE","guide file type, signature, or size is invalid");ProgramGuideAttachment f=new ProgramGuideAttachment();f.setTenantId(actor.tenantId());f.setProgramId(programId);f.setFilename(safeFilename(filename));f.setContentType(contentType);f.setSize(bytes.length);f.setUploadedBy(actor.employeeId());f.setContent(bytes.clone());return response(files.save(f));}
 @Transactional(readOnly=true)public List<GuideAttachmentResponse> list(Actor actor,UUID programId){access.program(actor,programId);return files.findAllByTenantIdAndProgramIdOrderByCreatedAtAsc(actor.tenantId(),programId).stream().map(this::response).toList();}
 @Transactional(readOnly=true)public ProgramGuideAttachment download(Actor actor,UUID id){ProgramGuideAttachment f=files.findByIdAndTenantId(id,actor.tenantId()).orElseThrow(()->new ApiException(ProgramErrorCode.PROGRAM_NOT_FOUND));access.program(actor,f.getProgramId());return f;}
 private GuideAttachmentResponse response(ProgramGuideAttachment f){return new GuideAttachmentResponse(f.getId(),f.getProgramId(),f.getFilename(),f.getContentType(),f.getSize(),f.getUploadedBy(),f.getCreatedAt());}private static String safeFilename(String n){String value=n==null?"guide":n.replace('\\','/');value=value.substring(value.lastIndexOf('/')+1).replaceAll("[\\r\\n]","_");return value.isBlank()?"guide":value;}private static boolean validMagic(String type,byte[] bytes){if("application/pdf".equals(type))return startsWith(bytes,new byte[]{'%','P','D','F','-'});if(type.startsWith("application/vnd.openxmlformats-officedocument"))return startsWith(bytes,new byte[]{'P','K'});if("text/plain".equals(type)){for(byte b:bytes)if(b==0)return false;return true;}return false;}private static boolean startsWith(byte[] bytes,byte[] prefix){if(bytes.length<prefix.length)return false;for(int i=0;i<prefix.length;i++)if(bytes[i]!=prefix[i])return false;return true;}
}
