package com.easyperformance.program;

import com.easyperformance.program.ProgramDtos.*;import com.easyperformance.program.ProgramTypes.*;import com.easyperformance.readmodel.entity.RmEmployee;import com.easyperformance.readmodel.repository.RmEmployeeRepository;import com.easyperformance.workflow.ActorAccess.Actor;import com.easyware.platform.error.ApiException;import org.springframework.beans.factory.ObjectProvider;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Instant;import java.util.*;
@Service
public class ProgramNotificationService{
 private final ProgramNotificationRepository notifications;private final RmEmployeeRepository employees;private final EvaluationProgramRepository programs;private final ProgramAccess access;private final ProgramMailSender mail;private final ProgramNotificationStatusService statuses;
 public ProgramNotificationService(ProgramNotificationRepository notifications,RmEmployeeRepository employees,EvaluationProgramRepository programs,ProgramAccess access,ObjectProvider<ProgramMailSender> mail,ProgramNotificationStatusService statuses){this.notifications=notifications;this.employees=employees;this.programs=programs;this.access=access;this.mail=mail.getIfAvailable();this.statuses=statuses;}
 @Transactional(readOnly=true)public List<NotificationPreview> preview(Actor actor,UUID programId,NotificationPreviewRequest request){access.requireOperator(actor);access.program(actor,programId);return recipients(actor,request).stream().map(e->new NotificationPreview(e.getId(),render(request.subjectTemplate(),request.companyName(),e.getName()),render(request.bodyTemplate(),request.companyName(),e.getName()))).toList();}
 @Transactional public NotificationQueueResponse queue(Actor actor,UUID programId,NotificationPreviewRequest request){access.requireOperator(actor);EvaluationProgram program=programs.findByIdAndTenantId(programId,actor.tenantId()).orElseThrow(()->new ApiException(ProgramErrorCode.PROGRAM_NOT_FOUND));List<UUID> ids=new ArrayList<>();NotificationStatus aggregate=request.channel()==NotificationChannel.EMAIL&&(mail==null||!mail.configured())?NotificationStatus.CONFIG_REQUIRED:request.channel()==NotificationChannel.EMAIL?NotificationStatus.READY:NotificationStatus.SENT;for(RmEmployee e:recipients(actor,request)){ProgramNotification n=new ProgramNotification();n.setTenantId(actor.tenantId());n.setProgramId(program.getId());n.setRecipientEmployeeId(e.getId());n.setChannel(request.channel());n.setSubject(render(request.subjectTemplate(),request.companyName(),e.getName()));n.setBody(render(request.bodyTemplate(),request.companyName(),e.getName()));n.setStatus(aggregate);if(aggregate==NotificationStatus.SENT)n.setSentAt(Instant.now());else if(aggregate==NotificationStatus.CONFIG_REQUIRED)n.setFailureReason("EMAIL_ADAPTER_NOT_CONFIGURED");n=notifications.save(n);ids.add(n.getId());}return new NotificationQueueResponse(ids.size(),aggregate,ids);}
 public NotificationDispatchResponse dispatch(Actor actor,UUID programId){access.requireOperator(actor);access.program(actor,programId);List<ProgramNotification> ready=notifications.findAllByTenantIdAndProgramIdAndChannelAndStatusOrderByCreatedAtAsc(actor.tenantId(),programId,NotificationChannel.EMAIL,NotificationStatus.READY);if(mail==null||!mail.configured())return new NotificationDispatchResponse(0,0,ready.size());int sent=0,failed=0;for(ProgramNotification n:ready){if(!statuses.claim(actor.tenantId(),n.getId()))continue;try{mail.send(actor.tenantId(),n.getRecipientEmployeeId(),n.getSubject(),n.getBody());statuses.sent(actor.tenantId(),n.getId());sent++;}catch(RuntimeException e){statuses.failed(actor.tenantId(),n.getId(),e.getMessage());failed++;}}return new NotificationDispatchResponse(sent,failed,0);}
 @Transactional(readOnly=true)public Page<NotificationResponse> mine(Actor actor,Pageable pageable){if(actor.employeeId()==null)throw new ApiException(ProgramErrorCode.PROGRAM_FORBIDDEN);return notifications.findAllByTenantIdAndRecipientEmployeeIdOrderByCreatedAtDesc(actor.tenantId(),actor.employeeId(),pageable).map(this::response);}
 @Transactional public NotificationResponse read(Actor actor,UUID id){ProgramNotification n=notifications.findByIdAndTenantId(id,actor.tenantId()).filter(x->x.getRecipientEmployeeId().equals(actor.employeeId())).orElseThrow(()->new ApiException(ProgramErrorCode.PROGRAM_FORBIDDEN));n.setReadAt(Instant.now());if(n.getChannel()==NotificationChannel.IN_APP)n.setStatus(NotificationStatus.READ);return response(notifications.save(n));}
 private List<RmEmployee> recipients(Actor actor,NotificationPreviewRequest request){return request.recipientEmployeeIds().stream().distinct().map(id->employees.findByIdAndTenantId(id,actor.tenantId()).filter(e->"ACTIVE".equalsIgnoreCase(e.getStatus())).orElseThrow(()->new ProgramRuleViolation("RECIPIENT","recipient is not active"))).toList();}
 private static String render(String template,String company,String employee){return template.replace("{companyName}",company).replace("{employeeName}",employee);}private NotificationResponse response(ProgramNotification n){return new NotificationResponse(n.getId(),n.getRecipientEmployeeId(),n.getChannel(),n.getStatus(),n.getSubject(),n.getBody(),n.getSentAt(),n.getReadAt());}
}
