package com.easyperformance.program;

import com.easyperformance.program.ProgramDtos.*;
import com.easyperformance.program.ProgramTypes.*;
import com.easyperformance.resources.ResourceDtos.CatalogKind;
import com.easyperformance.resources.ResourceIntegrationService;
import com.easyperformance.workflow.ActorAccess.Actor;
import com.easyware.platform.error.ApiException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Instant;
import java.util.*;

@Service
public class ProgramExecutionService {
    private final EvaluationProgramRepository programs;
    private final ProgramParticipantRepository participants;
    private final ProgramReviewerAssignmentRepository reviewers;
    private final ProgramGoalRepository goals;
    private final ProgramGoalEventRepository goalEvents;
    private final ProgramIntermediateReviewRepository intermediate;
    private final ProgramReviewSubmissionRepository submissions;
    private final ProgramCalculationRepository calculations;
    private final ProgramAdjustmentRepository adjustments;
    private final ProgramFeedbackRepository feedback;
    private final ProgramAccess access;
    private final ProgramRosterService roster;
    private final EvaluationProgramService programService;
    private final ResourceIntegrationService resources;
    private final ProgramJson json;
    private final ProgramAuditService audit;

    public ProgramExecutionService(EvaluationProgramRepository programs, ProgramParticipantRepository participants,
        ProgramReviewerAssignmentRepository reviewers, ProgramGoalRepository goals,
        ProgramGoalEventRepository goalEvents, ProgramIntermediateReviewRepository intermediate,
        ProgramReviewSubmissionRepository submissions, ProgramCalculationRepository calculations,
        ProgramAdjustmentRepository adjustments, ProgramFeedbackRepository feedback,
        ProgramAccess access, ProgramRosterService roster, EvaluationProgramService programService,
        ResourceIntegrationService resources, ProgramJson json, ProgramAuditService audit) {
        this.programs=programs; this.participants=participants; this.reviewers=reviewers; this.goals=goals;
        this.goalEvents=goalEvents; this.intermediate=intermediate; this.submissions=submissions;
        this.calculations=calculations; this.adjustments=adjustments; this.feedback=feedback;
        this.access=access; this.roster=roster; this.programService=programService; this.resources=resources;
        this.json=json; this.audit=audit;
    }

    @Transactional public GoalResponse createGoal(Actor actor, UUID participantId, GoalUpsertRequest request) {
        ProgramParticipant participant=access.participant(actor,participantId); requireOpen(actor,participant.getProgramId());
        if (!access.self(actor,participant)) requireRole(actor,participant,ReviewerRole.AGREEMENT_REVIEWER,0);
        ProgramGoal goal=new ProgramGoal(); goal.setTenantId(actor.tenantId()); goal.setProgramId(participant.getProgramId());
        goal.setParticipantId(participantId); applyGoalInput(actor,participant,goal,request);
        ensureGoalWeightAtMostOneHundred(actor.tenantId(),participantId,goal);
        goal=goals.save(goal); goalEvent(actor,goal,"CREATED",null);
        audit.record(actor,participant.getProgramId(),participantId,ProgramEventType.GOAL_CHANGED,"goal created",Map.of("goalId",goal.getId()));
        return goalResponse(goal);
    }

    @Transactional public GoalResponse updateGoal(Actor actor, UUID goalId, GoalUpsertRequest request) {
        ProgramGoal goal=requireGoal(actor,goalId); ProgramParticipant participant=access.participant(actor,goal.getParticipantId());
        requireOpen(actor,goal.getProgramId());
        if (!access.self(actor,participant)) requireRole(actor,participant,ReviewerRole.AGREEMENT_REVIEWER,0);
        if (goal.getStatus()!=GoalStatus.DRAFT && goal.getStatus()!=GoalStatus.RETURNED) throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED);
        applyGoalInput(actor,participant,goal,request); goal.setRevision(goal.getRevision()+1);
        ensureGoalWeightAtMostOneHundred(actor.tenantId(),participant.getId(),goal); goals.save(goal); goalEvent(actor,goal,"UPDATED",null);
        return goalResponse(goal);
    }

    @Transactional public GoalResponse saveGoalOpinion(Actor actor,UUID goalId,GoalOpinionRequest request){
        ProgramGoal goal=requireGoal(actor,goalId);ProgramParticipant participant=access.participant(actor,goal.getParticipantId());
        requireOpen(actor,goal.getProgramId());
        if(!access.self(actor,participant))requireRole(actor,participant,ReviewerRole.AGREEMENT_REVIEWER,0);
        if(goal.getStatus()==GoalStatus.AGREED||goal.getStatus()==GoalStatus.SELF_REPORTED)throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED);
        goal.setDraftOpinion(request.opinion());goals.save(goal);goalEvent(actor,goal,"OPINION_SAVED",request.opinion());return goalResponse(goal);
    }

    @Transactional public GoalResponse requestAgreement(Actor actor,UUID goalId){
        ProgramGoal goal=requireGoal(actor,goalId);ProgramParticipant participant=access.participant(actor,goal.getParticipantId());
        requireOpen(actor,goal.getProgramId());
        if(!access.self(actor,participant))throw new ApiException(ProgramErrorCode.PROGRAM_FORBIDDEN);
        ProgramConfiguration c=config(actor,goal.getProgramId());if(c.goalMode()!=GoalMode.AGREEMENT)throw new ApiException(ProgramErrorCode.PROGRAM_STAGE_INVALID);
        if(goal.getStatus()!=GoalStatus.DRAFT&&goal.getStatus()!=GoalStatus.RETURNED)throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED);
        ensureGoalWeightExactlyOneHundred(actor.tenantId(),participant.getId());goal.setStatus(GoalStatus.AGREEMENT_REQUESTED);goal.setRevision(goal.getRevision()+1);goals.save(goal);goalEvent(actor,goal,"AGREEMENT_REQUESTED",goal.getDraftOpinion());return goalResponse(goal);
    }

    @Transactional public GoalResponse decideGoal(Actor actor,UUID goalId,GoalDecisionRequest request){
        ProgramGoal goal=requireGoal(actor,goalId);ProgramParticipant participant=access.participant(actor,goal.getParticipantId());
        requireOpen(actor,goal.getProgramId());
        requireRole(actor,participant,ReviewerRole.AGREEMENT_REVIEWER,0);
        if(goal.getStatus()!=GoalStatus.AGREEMENT_REQUESTED)throw new ApiException(ProgramErrorCode.PROGRAM_STAGE_INVALID);
        goal.setStatus(request.approve()?GoalStatus.AGREED:GoalStatus.RETURNED);goal.setDecisionOpinion(request.opinion());goal.setRevision(goal.getRevision()+1);goals.save(goal);goalEvent(actor,goal,request.approve()?"AGREED":"RETURNED",request.opinion());
        if(request.approve()&&goals.findAllByTenantIdAndParticipantIdOrderByCreatedAtAsc(actor.tenantId(),participant.getId()).stream().allMatch(g->g.getStatus()==GoalStatus.AGREED))completeStage(participant,ProgramStage.GOAL);
        return goalResponse(goal);
    }

    @Transactional public GoalResponse selfReport(Actor actor,UUID goalId,GoalSelfReportRequest request){
        ProgramGoal goal=requireGoal(actor,goalId);ProgramParticipant participant=access.participant(actor,goal.getParticipantId());
        requireOpen(actor,goal.getProgramId());
        if(!access.self(actor,participant))throw new ApiException(ProgramErrorCode.PROGRAM_FORBIDDEN);
        ProgramConfiguration c=config(actor,goal.getProgramId());if(c.goalMode()!=GoalMode.SELF_REPORT)throw new ApiException(ProgramErrorCode.PROGRAM_STAGE_INVALID);
        ensureGoalWeightExactlyOneHundred(actor.tenantId(),participant.getId());
        if(goal.getAchievementLevels()!=null&&!json.achievementLevels(goal.getAchievementLevels()).isEmpty()&&json.achievementLevels(goal.getAchievementLevels()).stream().noneMatch(l->l.code().equals(request.achievedLevelCode())))throw new ProgramRuleViolation("ACHIEVEMENT_LEVEL","achieved level is not defined");
        List<TaskEvidenceSnapshot> evidence=evidence(actor,participant,request.taskIds());goal.setEvidenceJson(json.write(evidence));goal.setAchievedLevelCode(request.achievedLevelCode());goal.setAchievementSummary(request.achievementSummary());goal.setStatus(GoalStatus.SELF_REPORTED);goal.setRevision(goal.getRevision()+1);goals.save(goal);goalEvent(actor,goal,"SELF_REPORTED",request.achievementSummary());
        if(goals.findAllByTenantIdAndParticipantIdOrderByCreatedAtAsc(actor.tenantId(),participant.getId()).stream().allMatch(g->g.getStatus()==GoalStatus.SELF_REPORTED))completeStage(participant,ProgramStage.GOAL);return goalResponse(goal);
    }

    @Transactional(readOnly=true) public List<GoalResponse> goals(Actor actor,UUID participantId){ProgramParticipant p=access.participant(actor,participantId);return goals.findAllByTenantIdAndParticipantIdOrderByCreatedAtAsc(actor.tenantId(),p.getId()).stream().map(this::goalResponse).toList();}
    @Transactional(readOnly=true) public List<GoalHistoryResponse> goalHistory(Actor actor,UUID goalId){ProgramGoal goal=requireGoal(actor,goalId);access.participant(actor,goal.getParticipantId());return goalEvents.findAllByTenantIdAndGoalIdOrderByRevisionAscCreatedAtAsc(actor.tenantId(),goalId).stream().map(e->new GoalHistoryResponse(e.getId(),e.getGoalId(),e.getRevision(),e.getStatus(),e.getOperation(),e.getOpinion(),e.getActorEmployeeId(),e.getCreatedAt())).toList();}

    @Transactional public IntermediateResponse saveIntermediate(Actor actor,UUID participantId,IntermediateUpdateRequest request,boolean complete){
        ProgramParticipant p=access.participant(actor,participantId);requireOpen(actor,p.getProgramId());requireRole(actor,p,ReviewerRole.CHECKER,0);if(p.getCurrentStage()!=ProgramStage.INTERMEDIATE||p.getStageStatus()!=ProgramStageStatus.IN_PROGRESS)throw new ApiException(ProgramErrorCode.PROGRAM_STAGE_INVALID);
        ProgramIntermediateReview row=intermediate.findByTenantIdAndParticipantId(actor.tenantId(),participantId).orElseGet(ProgramIntermediateReview::new);if(row.getId()==null){row.setTenantId(actor.tenantId());row.setProgramId(p.getProgramId());row.setParticipantId(participantId);row.setCheckerEmployeeId(actor.employeeId());}
        if(row.getStatus()==SubmissionStatus.COMPLETED)throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED);row.setOpinion(request.opinion());row.setTaskEvidence(json.write(evidence(actor,p,request.taskIds())));if(complete){row.setStatus(SubmissionStatus.COMPLETED);row.setCompletedAt(Instant.now());completeStage(p,ProgramStage.INTERMEDIATE);}return intermediateResponse(intermediate.save(row));
    }
    @Transactional(readOnly=true) public IntermediateResponse intermediate(Actor actor,UUID participantId){ProgramParticipant p=access.participant(actor,participantId);return intermediate.findByTenantIdAndParticipantId(actor.tenantId(),p.getId()).map(this::intermediateResponse).orElse(null);}

    @Transactional public ReviewSubmissionResponse saveReview(Actor actor,UUID participantId,Integer round,ReviewSaveRequest request,boolean complete){
        ProgramParticipant p=access.participant(actor,participantId);EvaluationProgram program=complete?requireOpenLocked(actor,p.getProgramId()):requireOpen(actor,p.getProgramId());boolean self=p.getCurrentStage()==ProgramStage.SELF_REVIEW&&access.self(actor,p);ProgramReviewerAssignment assignment=null;ReviewerRole role;int actualRound;
        if(self){role=ReviewerRole.SELF;actualRound=0;}else{actualRound=round==null?p.getCurrentRound():round;assignment=requireRole(actor,p,ReviewerRole.REVIEWER,actualRound);role=ReviewerRole.REVIEWER;}
        if(p.getStageStatus()!=ProgramStageStatus.IN_PROGRESS||(role==ReviewerRole.SELF&&p.getCurrentStage()!=ProgramStage.SELF_REVIEW)||(role==ReviewerRole.REVIEWER&&p.getCurrentStage()!=ProgramStage.REVIEW))throw new ApiException(ProgramErrorCode.PROGRAM_STAGE_INVALID);
        String key=assignment==null?"SELF":assignment.getId().toString();ProgramReviewSubmission row=submissions.findByTenantIdAndParticipantIdAndReviewerAssignmentKeyAndRound(actor.tenantId(),p.getId(),key,actualRound).orElseGet(ProgramReviewSubmission::new);if(row.getId()!=null&&row.getStatus()==SubmissionStatus.COMPLETED)throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED);
        List<CommonItemInput> items=items(program,p,actualRound);List<ReviewItemAnswerResponse> answers=validateAnswers(config(program),items,request.answers(),complete);if(row.getId()==null){row.setTenantId(actor.tenantId());row.setProgramId(program.getId());row.setParticipantId(p.getId());row.setReviewerAssignmentId(assignment==null?null:assignment.getId());row.setReviewerAssignmentKey(key);row.setActorEmployeeId(actor.employeeId());row.setRole(role);row.setRound(actualRound);}row.setAnswersJson(json.write(answers));row.setOverallOpinion(request.overallOpinion());if(complete){row.setStatus(SubmissionStatus.COMPLETED);row.setCompletedAt(Instant.now());if(assignment!=null){assignment.setStatus(AssignmentStatus.COMPLETED);reviewers.save(assignment);}advanceAfterReview(actor,p,role,actualRound);}row=submissions.save(row);if(complete)audit.record(actor,p.getProgramId(),p.getId(),ProgramEventType.RESPONSE_COMPLETED,"review completed",Map.of("round",actualRound,"role",role));return submissionResponse(row);
    }

    @Transactional(readOnly=true) public ReviewContextResponse reviewContext(Actor actor,UUID participantId,Integer round){ProgramParticipant p=access.participant(actor,participantId);EvaluationProgram program=access.program(actor,p.getProgramId());int actual;if(access.operator(actor)){actual=round==null?p.getCurrentRound():round;}else if(access.self(actor,p)){actual=0;if(round!=null&&round!=0)throw new ApiException(ProgramErrorCode.PROGRAM_FORBIDDEN);}else{actual=round==null?p.getCurrentRound():round;requireRole(actor,p,ReviewerRole.REVIEWER,actual);}List<ProgramReviewSubmission> all=submissions.findAllByTenantIdAndParticipantIdOrderByRoundAsc(actor.tenantId(),p.getId());List<ReviewSubmissionResponse> visible=visiblePrevious(actor,p,program,all,actual);ReviewSubmissionResponse current=all.stream().filter(s->s.getRound()==actual&&Objects.equals(s.getActorEmployeeId(),actor.employeeId())).findFirst().map(this::submissionResponse).orElse(null);List<CommonItemInput> currentItems=items(program,p,actual);return new ReviewContextResponse(roster.response(actor.tenantId(),p),goals(actor,p.getId()),intermediate(actor,p.getId()),visible,current,currentItems,reviewScales(program,currentItems));}

    @Transactional public List<CalculationResponse> calculate(Actor actor,UUID programId,CalculationRunRequest request){access.requireOperator(actor);EvaluationProgram program=requireOpen(actor,programId);ProgramConfiguration config=config(program);Set<UUID> selected=request.participantIds()==null||request.participantIds().isEmpty()?null:new HashSet<>(request.participantIds());List<ProgramParticipant> candidates=participants.findAllByTenantIdAndProgramIdOrderByCreatedAtAsc(actor.tenantId(),programId).stream().filter(p->p.getStatus()==ParticipantStatus.ACTIVE&&(selected==null||selected.contains(p.getId()))).toList();List<RawCalculation> raw=new ArrayList<>();for(ProgramParticipant p:candidates){try{if(p.getCurrentStage()!=ProgramStage.CALCULATION||p.getStageStatus()!=ProgramStageStatus.IN_PROGRESS)throw new ProgramRuleViolation("CALCULATION_STAGE","participant is not ready for calculation");raw.add(raw(actor,program,config,p));}catch(ProgramRuleViolation e){if(!request.excludeIncomplete())throw e;}}
        if(raw.isEmpty())throw new ProgramRuleViolation("NO_CALCULABLE_PARTICIPANTS","no complete participants to calculate");normalize(config,raw);assignRelativeGrades(config,raw);List<CalculationResponse> out=new ArrayList<>();for(RawCalculation value:raw){int revision=calculations.findFirstByTenantIdAndParticipantIdOrderByRevisionDesc(actor.tenantId(),value.participant.getId()).map(c->c.getRevision()+1).orElse(1);ProgramCalculation c=new ProgramCalculation();c.setTenantId(actor.tenantId());c.setProgramId(programId);c.setParticipantId(value.participant.getId());c.setRevision(revision);c.setContributionsJson(json.write(value.contributions));c.setRawScore(value.raw);c.setNormalizedScore(value.normalized);c.setAdjustedScore(value.adjusted);c.setCalculatedGrade(value.grade);c.setStatus(CalculationStatus.FINAL);c.setFormula(value.formula);c.setWarningsJson(json.write(value.warnings));calculations.save(c);invalidateFeedback(actor,value.participant,"result recalculated");completeStage(value.participant,ProgramStage.CALCULATION);audit.record(actor,programId,value.participant.getId(),ProgramEventType.CALCULATED,request.reason(),Map.of("revision",revision,"score",value.adjusted,"grade",value.grade));out.add(calculationResponse(c));}return out;}
    @Transactional(readOnly=true) public List<CalculationResponse> calculations(Actor actor,UUID participantId){ProgramParticipant p=access.participant(actor,participantId);EvaluationProgram program=access.program(actor,p.getProgramId());List<ProgramCalculation> entities=calculations.findAllByTenantIdAndParticipantIdOrderByRevisionDesc(actor.tenantId(),p.getId());if(access.operator(actor))return entities.stream().map(this::calculationResponse).toList();if(access.self(actor,p)){if(program.getStatus()!=ProgramStatus.FINALIZED||!p.isResultPublished())throw new ApiException(ProgramErrorCode.RESULT_NOT_PUBLISHED);ProgramCalculation latestFinal=entities.stream().filter(c->c.getStatus()==CalculationStatus.FINAL).findFirst().orElseThrow(()->new ApiException(ProgramErrorCode.RESULT_NOT_PUBLISHED));ProgramAdjustment linked=adjustments.findFirstByTenantIdAndParticipantIdOrderByRevisionDesc(actor.tenantId(),p.getId()).filter(a->a.getStatus()==AdjustmentStatus.COMPLETED&&a.getCalculationId().equals(latestFinal.getId())).orElse(null);return List.of(memberCalculation(calculationResponse(latestFinal),linked,config(program).publication().memberResultVisibility()));}if(program.getStatus()!=ProgramStatus.OPEN)throw new ApiException(ProgramErrorCode.PROGRAM_FORBIDDEN);requireRole(actor,p,ReviewerRole.ADJUSTER,0);return entities.stream().map(this::calculationResponse).toList();}

    @Transactional public AdjustmentResponse saveAdjustment(Actor actor,UUID participantId,AdjustmentSaveRequest request,boolean complete){ProgramParticipant p=access.participant(actor,participantId);EvaluationProgram program=requireOpen(actor,p.getProgramId());if(!access.operator(actor))requireRole(actor,p,ReviewerRole.ADJUSTER,0);if(p.getCurrentStage()!=ProgramStage.CALIBRATION||p.getStageStatus()!=ProgramStageStatus.IN_PROGRESS)throw new ApiException(ProgramErrorCode.PROGRAM_STAGE_INVALID);ProgramCalculation calc=latest(actor,p);validateAdjustment(config(program),calc,request);ProgramAdjustment latestAdjustment=adjustments.findFirstByTenantIdAndParticipantIdOrderByRevisionDesc(actor.tenantId(),p.getId()).orElse(null);ProgramAdjustment a;if(latestAdjustment!=null&&latestAdjustment.getCalculationId().equals(calc.getId())){if(latestAdjustment.getStatus()==AdjustmentStatus.COMPLETED)throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED);a=latestAdjustment;}else{a=new ProgramAdjustment();a.setTenantId(actor.tenantId());a.setProgramId(program.getId());a.setParticipantId(p.getId());a.setRevision(latestAdjustment==null?1:latestAdjustment.getRevision()+1);a.setCalculationId(calc.getId());a.setBeforeScore(calc.getAdjustedScore());a.setBeforeGrade(calc.getCalculatedGrade());a.setActorEmployeeId(actor.employeeId());}a.setAdjustedScore(request.adjustedScore()==null?calc.getAdjustedScore():request.adjustedScore());a.setAdjustedGrade(request.adjustedGrade());a.setReason(request.reason());if(complete){a.setStatus(AdjustmentStatus.COMPLETED);a.setCompletedAt(Instant.now());completeStage(p,ProgramStage.CALIBRATION);}a=adjustments.save(a);audit.record(actor,p.getProgramId(),p.getId(),ProgramEventType.ADJUSTED,request.reason(),Map.of("revision",a.getRevision(),"calculationId",calc.getId(),"grade",request.adjustedGrade(),"complete",complete));return adjustmentResponse(a);}

    @Transactional public FeedbackResponse saveFeedback(Actor actor,UUID participantId,FeedbackSaveRequest request,boolean deliver){ProgramParticipant p=access.participant(actor,participantId);EvaluationProgram program=requireOpen(actor,p.getProgramId());if(!access.operator(actor))requireRole(actor,p,ReviewerRole.FINAL_FEEDBACK,0);if(p.getCurrentStage()!=ProgramStage.FEEDBACK||p.getStageStatus()!=ProgramStageStatus.IN_PROGRESS)throw new ApiException(ProgramErrorCode.PROGRAM_STAGE_INVALID);ProgramFeedback f=feedback.findByTenantIdAndParticipantId(actor.tenantId(),p.getId()).orElseGet(ProgramFeedback::new);if(f.getId()!=null&&f.getStatus()!=FeedbackStatus.DRAFT)throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED);if(f.getId()==null){f.setTenantId(actor.tenantId());f.setProgramId(program.getId());f.setParticipantId(p.getId());}f.setWriterEmployeeId(actor.employeeId());f.setComment(request.comment());if(deliver){f.setStatus(FeedbackStatus.DELIVERED);f.setDeliveredAt(Instant.now());}f=feedback.save(f);audit.record(actor,p.getProgramId(),p.getId(),ProgramEventType.FEEDBACK_CHANGED,deliver?"feedback delivered":"feedback saved",Map.of());return feedbackResponse(f);}
    @Transactional public FeedbackResponse agreeFeedback(Actor actor,UUID feedbackId){ProgramFeedback f=requireFeedback(actor,feedbackId);ProgramParticipant p=access.participant(actor,f.getParticipantId());requireOpen(actor,p.getProgramId());if(!access.self(actor,p)||f.getStatus()!=FeedbackStatus.DELIVERED)throw new ApiException(ProgramErrorCode.PROGRAM_FORBIDDEN);f.setStatus(FeedbackStatus.AGREED);feedback.save(f);completeStage(p,ProgramStage.FEEDBACK);return feedbackResponse(f);}
    @Transactional public FeedbackResponse appealFeedback(Actor actor,UUID feedbackId,FeedbackAppealRequest request){ProgramFeedback f=requireFeedback(actor,feedbackId);ProgramParticipant p=access.participant(actor,f.getParticipantId());requireOpen(actor,p.getProgramId());if(!access.self(actor,p)||f.getStatus()!=FeedbackStatus.DELIVERED)throw new ApiException(ProgramErrorCode.PROGRAM_FORBIDDEN);if(!config(actor,p.getProgramId()).publication().appealEnabled())throw new ApiException(ProgramErrorCode.PROGRAM_STAGE_INVALID);f.setAppealReason(request.reason());f.setStatus(FeedbackStatus.APPEALED);feedback.save(f);return feedbackResponse(f);}
    @Transactional public FeedbackResponse resolveFeedback(Actor actor,UUID feedbackId,FeedbackResolveRequest request){
        ProgramFeedback f=requireFeedback(actor,feedbackId);ProgramParticipant p=access.participant(actor,f.getParticipantId());
        requireOpen(actor,p.getProgramId());if(!access.operator(actor))requireRole(actor,p,ReviewerRole.FINAL_FEEDBACK,0);
        if(f.getStatus()!=FeedbackStatus.APPEALED)throw new ApiException(ProgramErrorCode.PROGRAM_STAGE_INVALID);
        if(request.resolution()==AppealResolution.SCORE_ADJUSTED){
            if(request.adjustedScore()==null||request.adjustedGrade()==null||request.adjustedGrade().isBlank())throw new ProgramRuleViolation("APPEAL_ADJUSTMENT_REQUIRED","adjustedScore and adjustedGrade are required for a score adjustment");
            ProgramConfiguration configuration=config(actor,p.getProgramId());ProgramCalculation previous=latest(actor,p);
            validateAdjustment(configuration,previous,new AdjustmentSaveRequest(request.adjustedScore(),request.adjustedGrade(),request.comment()));
            ProgramCalculation corrected=new ProgramCalculation();corrected.setTenantId(actor.tenantId());corrected.setProgramId(p.getProgramId());corrected.setParticipantId(p.getId());corrected.setRevision(previous.getRevision()+1);corrected.setContributionsJson(previous.getContributionsJson());corrected.setRawScore(previous.getRawScore());corrected.setNormalizedScore(previous.getNormalizedScore());corrected.setAdjustedScore(request.adjustedScore());corrected.setCalculatedGrade(request.adjustedGrade());corrected.setStatus(CalculationStatus.FINAL);corrected.setFormula(previous.getFormula()+"; appeal correction");corrected.setWarningsJson(json.write(List.of("APPEAL_CORRECTION")));calculations.save(corrected);
            if(configuration.stages().stream().anyMatch(s->s.stage()==ProgramStage.CALIBRATION&&s.enabled())){
                ProgramAdjustment prior=adjustments.findFirstByTenantIdAndParticipantIdOrderByRevisionDesc(actor.tenantId(),p.getId()).orElse(null);ProgramAdjustment correction=new ProgramAdjustment();correction.setTenantId(actor.tenantId());correction.setProgramId(p.getProgramId());correction.setParticipantId(p.getId());correction.setRevision(prior==null?1:prior.getRevision()+1);correction.setCalculationId(corrected.getId());correction.setBeforeScore(previous.getAdjustedScore());correction.setBeforeGrade(previous.getCalculatedGrade());correction.setAdjustedScore(request.adjustedScore());correction.setAdjustedGrade(request.adjustedGrade());correction.setReason(request.comment());correction.setStatus(AdjustmentStatus.COMPLETED);correction.setActorEmployeeId(actor.employeeId());correction.setCompletedAt(Instant.now());adjustments.save(correction);audit.record(actor,p.getProgramId(),p.getId(),ProgramEventType.ADJUSTED,"appeal correction",Map.of("revision",correction.getRevision(),"calculationId",corrected.getId()));
            }
            p.setResultPublished(false);participants.save(p);
        }
        f.setResolution(request.resolution());f.setResolutionComment(request.comment());f.setResolvedAt(Instant.now());f.setStatus(FeedbackStatus.RESOLVED);feedback.save(f);completeStage(p,ProgramStage.FEEDBACK);return feedbackResponse(f);
    }

    @Transactional(readOnly=true) public List<ParticipantResponse> selfParticipants(Actor actor,UUID programId){return access.selfParticipants(actor,programId).stream().map(p->roster.response(actor.tenantId(),p)).toList();}
    @Transactional(readOnly=true) public MyProgramWorkspaceResponse workspace(Actor actor,UUID programId,UUID participantId){ProgramParticipant p=participantId==null?access.self(actor,programId):access.self(actor,programId,participantId);EvaluationProgram program=access.program(actor,programId);List<ReviewSubmissionResponse> own=submissions.findAllByTenantIdAndParticipantIdOrderByRoundAsc(actor.tenantId(),p.getId()).stream().filter(s->Objects.equals(s.getActorEmployeeId(),actor.employeeId())).map(this::submissionResponse).toList();MemberResultVisibility visibility=config(program).publication().memberResultVisibility();ProgramCalculation latestCalculation=p.isResultPublished()?calculations.findAllByTenantIdAndParticipantIdOrderByRevisionDesc(actor.tenantId(),p.getId()).stream().filter(c->c.getStatus()==CalculationStatus.FINAL).findFirst().orElse(null):null;ProgramAdjustment linked=latestCalculation==null?null:adjustments.findFirstByTenantIdAndParticipantIdOrderByRevisionDesc(actor.tenantId(),p.getId()).filter(a->a.getCalculationId().equals(latestCalculation.getId())&&a.getStatus()==AdjustmentStatus.COMPLETED).orElse(null);CalculationResponse calculation=latestCalculation==null?null:memberCalculation(calculationResponse(latestCalculation),linked,visibility);ProgramFeedback feedEntity=feedback.findByTenantIdAndParticipantId(actor.tenantId(),p.getId()).filter(f->f.getStatus()!=FeedbackStatus.DRAFT).orElse(null);FeedbackResponse feed=feedEntity==null?null:feedbackResponse(feedEntity);return new MyProgramWorkspaceResponse(programService.memberOverview(program),roster.response(actor.tenantId(),p),goals(actor,p.getId()),intermediate(actor,p.getId()),own,calculation,null,feed,allowed(actor,p,feedEntity),blockers(actor,p));}

    @Transactional public MyProgramWorkspaceResponse employeePreview(Actor actor,UUID participantId){access.requireOperator(actor);ProgramParticipant p=access.participant(actor,participantId);EvaluationProgram program=access.program(actor,p.getProgramId());List<ReviewSubmissionResponse> own=submissions.findAllByTenantIdAndParticipantIdOrderByRoundAsc(actor.tenantId(),p.getId()).stream().filter(s->s.getRole()==ReviewerRole.SELF).map(this::submissionResponse).toList();MemberResultVisibility visibility=config(program).publication().memberResultVisibility();ProgramCalculation latestCalculation=p.isResultPublished()?calculations.findAllByTenantIdAndParticipantIdOrderByRevisionDesc(actor.tenantId(),p.getId()).stream().filter(c->c.getStatus()==CalculationStatus.FINAL).findFirst().orElse(null):null;ProgramAdjustment linked=latestCalculation==null?null:adjustments.findFirstByTenantIdAndParticipantIdOrderByRevisionDesc(actor.tenantId(),p.getId()).filter(a->a.getCalculationId().equals(latestCalculation.getId())&&a.getStatus()==AdjustmentStatus.COMPLETED).orElse(null);CalculationResponse calculation=latestCalculation==null?null:memberCalculation(calculationResponse(latestCalculation),linked,visibility);ProgramFeedback feedEntity=feedback.findByTenantIdAndParticipantId(actor.tenantId(),p.getId()).filter(f->f.getStatus()!=FeedbackStatus.DRAFT).orElse(null);audit.record(actor,p.getProgramId(),p.getId(),ProgramEventType.EMPLOYEE_PREVIEWED,"employee workspace previewed",Map.of());return new MyProgramWorkspaceResponse(programService.memberOverview(program),roster.response(actor.tenantId(),p),goals(actor,p.getId()),intermediate(actor,p.getId()),own,calculation,null,feedEntity==null?null:feedbackResponse(feedEntity),List.of(),blockers(actor,p));}

    @Transactional(readOnly=true) public FeedbackResponse feedback(Actor actor,UUID participantId){ProgramParticipant p=access.participant(actor,participantId);ProgramFeedback row=feedback.findByTenantIdAndParticipantId(actor.tenantId(),p.getId()).orElse(null);if(row==null)return null;if(access.operator(actor))return feedbackResponse(row);if(access.self(actor,p))return row.getStatus()==FeedbackStatus.DRAFT?null:feedbackResponse(row);boolean finalAssignee=actor.employeeId()!=null&&reviewers.findByTenantIdAndParticipantIdAndRoleAndRoundAndStatusNot(actor.tenantId(),p.getId(),ReviewerRole.FINAL_FEEDBACK,0,AssignmentStatus.REVOKED).filter(r->r.getReviewerEmployeeId().equals(actor.employeeId())).isPresent();if(!finalAssignee&&!Objects.equals(row.getWriterEmployeeId(),actor.employeeId()))throw new ApiException(ProgramErrorCode.PROGRAM_FORBIDDEN);return feedbackResponse(row);}

    private void applyGoalInput(Actor actor,ProgramParticipant p,ProgramGoal goal,GoalUpsertRequest input){List<AchievementLevelInput> levels=input.achievementLevels()==null?List.of():input.achievementLevels();if(input.catalogItemId()!=null){CatalogKind kind=config(actor,p.getProgramId()).calculation().componentWeights().stream().anyMatch(w->"COMPETENCY".equals(w.component()))?CatalogKind.COMPETENCY:CatalogKind.PERFORMANCE;var selected=resources.requireActiveCatalog(actor.tenantId(),input.catalogItemId(),kind);levels=selected.achievementLevels().stream().map(l->new AchievementLevelInput(l.code(),l.label(),l.minValue())).toList();}if(input.departmentGoalId()!=null){var selected=resources.requireVisibleDepartmentGoal(actor.tenantId(),p.getEmployeeId(),input.departmentGoalId());if(levels.isEmpty())levels=selected.achievementLevels().stream().map(l->new AchievementLevelInput(l.code(),l.label(),l.minValue())).toList();}goal.setCatalogItemId(input.catalogItemId());goal.setDepartmentGoalId(input.departmentGoalId());goal.setTitle(input.title());goal.setDefinition(input.definition());goal.setWeightPercent(input.weightPercent());goal.setTargetValue(input.targetValue());goal.setUnit(input.unit());goal.setAchievementLevels(json.write(levels));}
    private List<TaskEvidenceSnapshot> evidence(Actor actor,ProgramParticipant p,List<UUID> taskIds){return resources.taskEvidence(actor.tenantId(),p.getEmployeeId(),taskIds==null?List.of():taskIds).stream().map(t->new TaskEvidenceSnapshot(t.taskId(),t.title(),t.status(),t.progressPercent(),t.occurredAt(),t.summary())).toList();}
    private List<CommonItemInput> items(EvaluationProgram program,ProgramParticipant p,int round){ProgramConfiguration c=config(program);List<CommonItemInput> configured=c.commonItems().stream().filter(i->i.groupId().equals(p.getGroupId())&&i.round()==round).toList();if(!configured.isEmpty())return configured;if(program.getKind()==EvaluationKind.PERFORMANCE){return goals.findAllByTenantIdAndParticipantIdOrderByCreatedAtAsc(p.getTenantId(),p.getId()).stream().map(g->new CommonItemInput(g.getId(),p.getGroupId(),round,g.getCatalogItemId(),g.getTitle(),g.getDefinition(),g.getWeightPercent(),c.calculation().inputScaleId(),0,false)).toList();}return List.of();}
    private List<ReviewScaleOverview> reviewScales(EvaluationProgram program,List<CommonItemInput> items){Set<UUID> ids=items.stream().map(CommonItemInput::scaleId).collect(java.util.stream.Collectors.toCollection(LinkedHashSet::new));return config(program).scales().stream().filter(s->ids.contains(s.id())).map(s->new ReviewScaleOverview(s.id(),s.name(),s.kind(),s.levels().stream().map(l->new MemberScaleLevel(l.code(),l.label(),l.color())).toList())).toList();}
    private List<ReviewItemAnswerResponse> validateAnswers(ProgramConfiguration c,List<CommonItemInput> items,List<ReviewItemAnswerInput> answers,boolean complete){Map<UUID,ReviewItemAnswerInput> supplied=new LinkedHashMap<>();answers.forEach(a->{if(supplied.put(a.itemId(),a)!=null)throw new ProgramRuleViolation("DUPLICATE_ANSWER","duplicate answer");});List<ReviewItemAnswerResponse> out=new ArrayList<>();for(CommonItemInput item:items){ReviewItemAnswerInput a=supplied.remove(item.id());if(a==null){if(complete)throw new ProgramRuleViolation("ANSWER_REQUIRED","all items require an answer");continue;}BigDecimal score=answerScore(c,item,a);if(score.compareTo(BigDecimal.ZERO)<0||score.compareTo(new BigDecimal("100"))>0)throw new ProgramRuleViolation("SCORE_RANGE","converted score must be 0..100");if(complete&&item.opinionRequired()&&(a.opinion()==null||a.opinion().isBlank()))throw new ProgramRuleViolation("OPINION_REQUIRED","item opinion is required");out.add(new ReviewItemAnswerResponse(item.id(),item.title(),item.weightPercent(),a.scaleCode(),score,a.opinion()));}if(!supplied.isEmpty())throw new ProgramRuleViolation("UNKNOWN_ITEM","answer contains an item outside the frozen form");return out;}
    private BigDecimal answerScore(ProgramConfiguration c,CommonItemInput item,ReviewItemAnswerInput answer){
        ScaleDefinitionInput scale=c.scales().stream().filter(s->s.id().equals(item.scaleId())).findFirst()
            .orElseThrow(()->new ProgramRuleViolation("SCALE_REFERENCE","scale missing"));
        return ProgramScoreCalculator.inputScore(scale,answer);
    }
    private RawCalculation raw(Actor actor,EvaluationProgram program,ProgramConfiguration c,ProgramParticipant p){List<ProgramReviewerAssignment> activeReviewers=reviewers.findAllByTenantIdAndParticipantIdAndStatusNotOrderByRoleAscRoundAsc(actor.tenantId(),p.getId(),AssignmentStatus.REVOKED).stream().filter(a->a.getRole()==ReviewerRole.REVIEWER).toList();List<ProgramReviewSubmission> completed=submissions.findAllByTenantIdAndParticipantIdOrderByRoundAsc(actor.tenantId(),p.getId()).stream().filter(s->s.getStatus()==SubmissionStatus.COMPLETED&&s.getRole()==ReviewerRole.REVIEWER).toList();validateReviewerCompletion(activeReviewers,completed);Map<UUID,ProgramReviewSubmission> completedByAssignment=completed.stream().collect(java.util.stream.Collectors.toMap(ProgramReviewSubmission::getReviewerAssignmentId,java.util.function.Function.identity()));List<ScoreContribution> contributions=new ArrayList<>();for(ProgramReviewerAssignment assignment:activeReviewers){ProgramReviewSubmission s=completedByAssignment.get(assignment.getId());List<ReviewItemAnswerResponse> answers=json.answers(s.getAnswersJson());BigDecimal denominator=answers.stream().map(ReviewItemAnswerResponse::weightPercent).reduce(BigDecimal.ZERO,BigDecimal::add);if(denominator.compareTo(BigDecimal.ZERO)==0)throw new ProgramRuleViolation("ZERO_DENOMINATOR","item weight denominator is zero");BigDecimal score=answers.stream().map(a->a.numericScore().multiply(a.weightPercent())).reduce(BigDecimal.ZERO,BigDecimal::add).divide(denominator,4,RoundingMode.HALF_UP);contributions.add(new ScoreContribution("REVIEWER_"+s.getRound(),score,assignment.getWeightPercent()));}RevieweeGroupInput group=c.groups().stream().filter(g->g.id().equals(p.getGroupId())).findFirst().orElseThrow(()->new ProgramRuleViolation("GROUP_MISSING","participant group missing"));ReviewerWeightPlanInput plan=group.reviewerWeightPlans().stream().filter(w->w.actualReviewerCount()==activeReviewers.size()).findFirst().orElseThrow(()->new ProgramRuleViolation("WEIGHT_PLAN_MISSING","weight plan missing"));if(c.calculation().departmentPerformanceEnabled()&&plan.departmentWeight()!=null&&plan.departmentWeight().compareTo(BigDecimal.ZERO)>0){String grade=departmentGrade(c,p);BigDecimal score=gradeScore(c,grade,c.calculation().departmentResultScaleId());contributions.add(new ScoreContribution("DEPARTMENT_PERFORMANCE",score,plan.departmentWeight()));}ScoreCalculationResult score=ProgramScoreCalculator.weightedAverage(contributions);String grade=gradeFor(c,score.score());return new RawCalculation(p,contributions,score.score(),score.score(),score.score(),grade,"sum(score*weight)/sum(weight)",new ArrayList<>());}
    static void validateReviewerCompletion(List<ProgramReviewerAssignment> activeReviewers,List<ProgramReviewSubmission> completed){if(activeReviewers.isEmpty())throw new ProgramRuleViolation("REVIEW_INCOMPLETE","reviewer assignments are missing");Set<UUID> assignmentIds=new HashSet<>();for(int index=0;index<activeReviewers.size();index++){ProgramReviewerAssignment assignment=activeReviewers.get(index);if(assignment.getRound()!=index+1||assignment.getStatus()!=AssignmentStatus.COMPLETED||!assignmentIds.add(assignment.getId()))throw new ProgramRuleViolation("REVIEW_INCOMPLETE","active reviewer rounds must be contiguous and completed");}Set<UUID> submittedIds=new HashSet<>();for(ProgramReviewSubmission submission:completed){if(submission.getReviewerAssignmentId()==null||!assignmentIds.contains(submission.getReviewerAssignmentId()))continue;if(submission.getRound()<1||!submittedIds.add(submission.getReviewerAssignmentId()))throw new ProgramRuleViolation("REVIEW_INCOMPLETE","completed review does not match an active reviewer assignment");ProgramReviewerAssignment assignment=activeReviewers.stream().filter(a->a.getId().equals(submission.getReviewerAssignmentId())).findFirst().orElseThrow();if(assignment.getRound()!=submission.getRound())throw new ProgramRuleViolation("REVIEW_INCOMPLETE","completed review round does not match its assignment");}if(!submittedIds.equals(assignmentIds))throw new ProgramRuleViolation("REVIEW_INCOMPLETE","all active reviewer assignments must be completed");}
    private void normalize(ProgramConfiguration config, List<RawCalculation> rows) {
        if (config.calculation().adjustmentMethod() == AdjustmentMethod.NONE) return;
        List<RawCalculation> targets = rows.stream().filter(row -> targeted(config, row.participant)).toList();
        String warning = normalizationPopulationWarning(config.calculation().adjustmentMethod(), targets.size());
        if (warning != null) { rows.forEach(row -> row.warnings.add(warning)); return; }
        Map<String, List<RawCalculation>> populations = new LinkedHashMap<>();
        for (RawCalculation row : targets) {
            String population = config.calculation().populationBasis() == PopulationBasis.DEPARTMENT
                ? String.valueOf(row.participant.getOrgUnitId()) : departmentGroupId(config, row.participant);
            String key = population + ":" + row.participant.getGroupId();
            populations.computeIfAbsent(key, ignored -> new ArrayList<>()).add(row);
        }
        for (List<RawCalculation> population : populations.values()) {
            BigDecimal count = BigDecimal.valueOf(population.size());
            BigDecimal mean = population.stream().map(row -> row.raw).reduce(BigDecimal.ZERO, BigDecimal::add)
                .divide(count, 8, RoundingMode.HALF_UP);
            BigDecimal variance = population.stream().map(row -> row.raw.subtract(mean).pow(2))
                .reduce(BigDecimal.ZERO, BigDecimal::add).divide(count, 8, RoundingMode.HALF_UP);
            double deviation = Math.sqrt(variance.doubleValue());
            for (RawCalculation row : population) {
                if (config.calculation().adjustmentMethod() == AdjustmentMethod.MEAN) {
                    row.normalized = row.raw.add(config.calculation().targetMean().subtract(mean));
                    row.formula = "raw + (targetMean - configuredPopulationMean)";
                } else if (deviation == 0) {
                    row.warnings.add("ZERO_STANDARD_DEVIATION");
                } else {
                    row.normalized = row.raw.subtract(mean).divide(BigDecimal.valueOf(deviation), 8, RoundingMode.HALF_UP)
                        .multiply(config.calculation().targetStandardDeviation()).add(config.calculation().targetMean());
                    row.formula = "((raw-configuredPopulationMean)/configuredPopulationStdDev)*targetStdDev+targetMean";
                }
                row.adjusted = clamp(row.normalized);
                row.grade = gradeFor(config, row.adjusted);
            }
        }
    }

    static String normalizationPopulationWarning(AdjustmentMethod method,int targetCount){return method!=AdjustmentMethod.NONE&&targetCount==0?"NO_ADJUSTMENT_TARGETS":null;}
    private void assignRelativeGrades(ProgramConfiguration c,List<RawCalculation> rows){Map<String,List<RawCalculation>> populations=new LinkedHashMap<>();for(RawCalculation r:rows){RevieweeGroupInput g=c.groups().stream().filter(x->x.id().equals(r.participant.getGroupId())).findFirst().orElseThrow();if(g.evaluationMethod()!=EvaluationMethod.RELATIVE)continue;String key=(c.calculation().populationBasis()==PopulationBasis.DEPARTMENT?String.valueOf(r.participant.getOrgUnitId()):departmentGroupId(c,r.participant))+":"+g.id();populations.computeIfAbsent(key,k->new ArrayList<>()).add(r);}List<String> gradeOrder=c.scales().stream().filter(s->s.id().equals(c.calculation().resultScaleId())).findFirst().orElseThrow(()->new ProgramRuleViolation("RESULT_SCALE","result scale is missing")).levels().stream().map(ScaleLevelInput::code).toList();for(List<RawCalculation> population:populations.values()){AllocationRowInput plan=c.allocationRows().stream().filter(a->a.populationSize()==population.size()).findFirst().orElseThrow(()->new ProgramRuleViolation("ALLOCATION_MISSING","exact allocation row is missing for population "+population.size()));population.sort(Comparator.comparing((RawCalculation r)->r.adjusted).reversed().thenComparing(r->r.participant.getEmployeeId()));int at=0;for(String grade:gradeOrder)for(int i=0;i<plan.gradeHeadcounts().getOrDefault(grade,0);i++)population.get(at++).grade=grade;}}
    private void validateAdjustment(ProgramConfiguration c,ProgramCalculation calc,AdjustmentSaveRequest r){if(!c.publication().scoreAdjustmentAllowed()&&r.adjustedScore()!=null&&r.adjustedScore().compareTo(calc.getAdjustedScore())!=0)throw new ProgramRuleViolation("SCORE_ADJUSTMENT_DISABLED","score adjustment is disabled");if(r.adjustedScore()!=null&&(r.adjustedScore().compareTo(BigDecimal.ZERO)<0||r.adjustedScore().compareTo(new BigDecimal("100"))>0))throw new ProgramRuleViolation("SCORE_RANGE","adjusted score must be 0..100");Integer max=c.publication().maximumGradeStepAdjustment();if(max!=null&&gradeDistance(c,calc.getCalculatedGrade(),r.adjustedGrade())>max)throw new ProgramRuleViolation("GRADE_STEP_LIMIT","grade adjustment exceeds configured maximum");}
    private void advanceAfterReview(Actor actor,ProgramParticipant p,ReviewerRole role,int round){if(role==ReviewerRole.SELF){completeStage(p,ProgramStage.SELF_REVIEW);return;}boolean next=reviewers.findAllByTenantIdAndParticipantIdAndStatusNotOrderByRoleAscRoundAsc(actor.tenantId(),p.getId(),AssignmentStatus.REVOKED).stream().anyMatch(r->r.getRole()==ReviewerRole.REVIEWER&&r.getRound()==round+1);if(next){p.setCurrentRound(round+1);p.setStageStatus(ProgramStageStatus.IN_PROGRESS);participants.save(p);}else completeStage(p,ProgramStage.REVIEW);}
    private List<ReviewSubmissionResponse> visiblePrevious(Actor actor,ProgramParticipant p,EvaluationProgram program,List<ProgramReviewSubmission> all,int currentRound){if(access.operator(actor))return all.stream().map(this::submissionResponse).toList();PreviousRoundVisibility policy=config(program).publication().previousRoundVisibility();return all.stream().filter(s->s.getRound()<currentRound&&s.getStatus()==SubmissionStatus.COMPLETED).map(s->{ReviewSubmissionResponse full=submissionResponse(s);if(policy==PreviousRoundVisibility.HIDDEN)return null;if(policy==PreviousRoundVisibility.SCORE_ONLY)return new ReviewSubmissionResponse(full.id(),full.participantId(),full.reviewerAssignmentId(),full.role(),full.round(),full.answers().stream().map(a->new ReviewItemAnswerResponse(a.itemId(),a.title(),a.weightPercent(),a.scaleCode(),a.numericScore(),null)).toList(),null,full.status(),full.completedAt(),full.rowVersion());return full;}).filter(Objects::nonNull).toList();}
    private void completeStage(ProgramParticipant p,ProgramStage stage){if(p.getCurrentStage()==stage){p.setStageStatus(ProgramStageStatus.COMPLETED);participants.save(p);}}
    private void invalidateFeedback(Actor actor,ProgramParticipant p,String reason){feedback.findByTenantIdAndParticipantId(actor.tenantId(),p.getId()).filter(f->f.getStatus()!=FeedbackStatus.DRAFT).ifPresent(f->{audit.record(actor,p.getProgramId(),p.getId(),ProgramEventType.FEEDBACK_INVALIDATED,reason,feedbackResponse(f));f.setStatus(FeedbackStatus.DRAFT);f.setComment(null);f.setAppealReason(null);f.setResolution(null);f.setResolutionComment(null);f.setDeliveredAt(null);f.setResolvedAt(null);feedback.save(f);});}
    private ProgramReviewerAssignment requireRole(Actor actor,ProgramParticipant p,ReviewerRole role,int round){if(actor.employeeId()==null)throw new ApiException(ProgramErrorCode.PROGRAM_FORBIDDEN);return reviewers.findByTenantIdAndParticipantIdAndRoleAndRoundAndStatusNot(actor.tenantId(),p.getId(),role,round,AssignmentStatus.REVOKED).filter(r->r.getReviewerEmployeeId().equals(actor.employeeId())).orElseThrow(()->new ApiException(ProgramErrorCode.PROGRAM_FORBIDDEN));}
    private EvaluationProgram requireOpen(Actor actor,UUID id){return requireOpenLocked(actor,id);}
    private EvaluationProgram requireOpenLocked(Actor actor,UUID id){EvaluationProgram p=programs.findLocked(id,actor.tenantId()).orElseThrow(()->new ApiException(ProgramErrorCode.PROGRAM_NOT_FOUND));if(p.getStatus()!=ProgramStatus.OPEN)throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED);return p;}
    private ProgramGoal requireGoal(Actor actor,UUID id){return goals.findByIdAndTenantId(id,actor.tenantId()).orElseThrow(()->new ApiException(ProgramErrorCode.GOAL_NOT_FOUND));}
    private ProgramFeedback requireFeedback(Actor actor,UUID id){return feedback.findByIdAndTenantId(id,actor.tenantId()).orElseThrow(()->new ApiException(ProgramErrorCode.PROGRAM_FEEDBACK_NOT_FOUND));}
    private ProgramCalculation latest(Actor actor,ProgramParticipant p){return calculations.findFirstByTenantIdAndParticipantIdOrderByRevisionDesc(actor.tenantId(),p.getId()).orElseThrow(()->new ProgramRuleViolation("CALCULATION_REQUIRED","calculation is required"));}
    private ProgramConfiguration config(Actor actor,UUID id){return config(access.program(actor,id));}private ProgramConfiguration config(EvaluationProgram p){return json.configuration(p.getDefinitionJson());}
    private void ensureGoalWeightAtMostOneHundred(UUID tenant,UUID participant,ProgramGoal changing){BigDecimal sum=goals.findAllByTenantIdAndParticipantIdOrderByCreatedAtAsc(tenant,participant).stream().filter(g->!g.getId().equals(changing.getId())).map(ProgramGoal::getWeightPercent).reduce(BigDecimal.ZERO,BigDecimal::add).add(changing.getWeightPercent());if(sum.compareTo(new BigDecimal("100"))>0)throw new ProgramRuleViolation("GOAL_WEIGHT_SUM","goal weights cannot exceed 100");}
    private void ensureGoalWeightExactlyOneHundred(UUID tenant,UUID participant){BigDecimal sum=goals.findAllByTenantIdAndParticipantIdOrderByCreatedAtAsc(tenant,participant).stream().map(ProgramGoal::getWeightPercent).reduce(BigDecimal.ZERO,BigDecimal::add);if(sum.compareTo(new BigDecimal("100"))!=0)throw new ProgramRuleViolation("GOAL_WEIGHT_SUM","goal weights must total 100");}
    private void goalEvent(Actor actor,ProgramGoal goal,String operation,String opinion){ProgramGoalEvent e=new ProgramGoalEvent();e.setTenantId(actor.tenantId());e.setGoalId(goal.getId());e.setRevision(goal.getRevision());e.setStatus(goal.getStatus());e.setOperation(operation);e.setOpinion(opinion);e.setActorEmployeeId(actor.employeeId());goalEvents.save(e);}
    private GoalResponse goalResponse(ProgramGoal g){return new GoalResponse(g.getId(),g.getParticipantId(),g.getCatalogItemId(),g.getDepartmentGoalId(),g.getTitle(),g.getDefinition(),g.getWeightPercent(),g.getTargetValue(),g.getUnit(),json.achievementLevels(g.getAchievementLevels()),g.getStatus(),g.getDraftOpinion(),g.getDecisionOpinion(),g.getAchievedLevelCode(),g.getAchievementSummary(),json.taskEvidence(g.getEvidenceJson()),g.getRevision(),g.getRowVersion(),g.getUpdatedAt());}
    private IntermediateResponse intermediateResponse(ProgramIntermediateReview r){return new IntermediateResponse(r.getId(),r.getParticipantId(),r.getCheckerEmployeeId(),r.getOpinion(),json.taskEvidence(r.getTaskEvidence()),r.getStatus(),r.getCompletedAt(),r.getRowVersion());}
    private ReviewSubmissionResponse submissionResponse(ProgramReviewSubmission s){return new ReviewSubmissionResponse(s.getId(),s.getParticipantId(),s.getReviewerAssignmentId(),s.getRole(),s.getRound(),json.answers(s.getAnswersJson()),s.getOverallOpinion(),s.getStatus(),s.getCompletedAt(),s.getRowVersion());}
    CalculationResponse calculationResponse(ProgramCalculation c){return new CalculationResponse(c.getId(),c.getParticipantId(),c.getRevision(),json.contributions(c.getContributionsJson()),c.getRawScore(),c.getNormalizedScore(),c.getAdjustedScore(),c.getCalculatedGrade(),c.getStatus(),c.getFormula(),json.strings(c.getWarningsJson()),c.getCalculatedAt());}
    AdjustmentResponse adjustmentResponse(ProgramAdjustment a){return new AdjustmentResponse(a.getId(),a.getParticipantId(),a.getRevision(),a.getCalculationId(),a.getBeforeScore(),a.getBeforeGrade(),a.getAdjustedScore(),a.getAdjustedGrade(),a.getReason(),a.getStatus(),a.getActorEmployeeId(),a.getCompletedAt(),a.getRowVersion());}
    private CalculationResponse memberCalculation(CalculationResponse r,ProgramAdjustment adjustment,MemberResultVisibility visibility){BigDecimal score=adjustment==null?r.adjustedScore():adjustment.getAdjustedScore();String grade=adjustment==null?r.calculatedGrade():adjustment.getAdjustedGrade();return new CalculationResponse(r.id(),r.participantId(),r.revision(),List.of(),null,null,visibility==MemberResultVisibility.SCORE_AND_GRADE?score:null,grade,r.status(),null,List.of(),r.calculatedAt());}
    FeedbackResponse feedbackResponse(ProgramFeedback f){return new FeedbackResponse(f.getId(),f.getParticipantId(),f.getWriterEmployeeId(),f.getComment(),f.getStatus(),f.getAppealReason(),f.getResolution(),f.getResolutionComment(),f.getDeliveredAt(),f.getResolvedAt(),f.getRowVersion());}
    private List<String> allowed(Actor a,ProgramParticipant p,ProgramFeedback f){List<String> out=new ArrayList<>();if(p.getStageStatus()==ProgramStageStatus.IN_PROGRESS){if(p.getCurrentStage()==ProgramStage.GOAL)out.add("EDIT_GOALS");if(p.getCurrentStage()==ProgramStage.SELF_REVIEW)out.add("EDIT_SELF_REVIEW");}if(f!=null&&f.getStatus()==FeedbackStatus.DELIVERED){out.add("AGREE_FEEDBACK");if(config(a,p.getProgramId()).publication().appealEnabled())out.add("APPEAL_FEEDBACK");}return out;}
    private List<String> blockers(Actor a,ProgramParticipant p){List<String> out=new ArrayList<>();if(p.getGroupId()==null)out.add("GROUP_UNMATCHED");if(p.getStatus()!=ParticipantStatus.ACTIVE)out.add("PARTICIPANT_NOT_ACTIVE");return out;}
    private boolean targeted(ProgramConfiguration c,ProgramParticipant p){RevieweeGroupInput g=c.groups().stream().filter(x->x.id().equals(p.getGroupId())).findFirst().orElseThrow();return c.calculation().adjustmentTarget()==AdjustmentTarget.ALL||(c.calculation().adjustmentTarget()==AdjustmentTarget.ABSOLUTE_ONLY&&g.evaluationMethod()==EvaluationMethod.ABSOLUTE)||(c.calculation().adjustmentTarget()==AdjustmentTarget.RELATIVE_ONLY&&g.evaluationMethod()==EvaluationMethod.RELATIVE);}
    private String gradeFor(ProgramConfiguration c,BigDecimal score){ScaleDefinitionInput scale=c.scales().stream().filter(s->s.id().equals(c.calculation().resultScaleId())).findFirst().orElseThrow();return scale.levels().stream().filter(l->(l.lowerExclusive()==null||score.compareTo(l.lowerExclusive())>0)&&(l.upperInclusive()==null||score.compareTo(l.upperInclusive())<=0)).map(ScaleLevelInput::code).findFirst().orElseThrow(()->new ProgramRuleViolation("GRADE_BAND","score does not fit result scale"));}
    private BigDecimal gradeScore(ProgramConfiguration c,String grade,UUID scaleId){if(scaleId==null)throw new ProgramRuleViolation("DEPARTMENT_SCALE","department result scale required");return c.scales().stream().filter(s->s.id().equals(scaleId)).flatMap(s->s.levels().stream()).filter(l->l.code().equals(grade)).map(ScaleLevelInput::convertedScore).filter(Objects::nonNull).findFirst().orElseThrow(()->new ProgramRuleViolation("DEPARTMENT_GRADE","department grade has no converted score"));}
    private String departmentGrade(ProgramConfiguration c,ProgramParticipant p){return c.departmentPerformanceGroups().stream().filter(g->ProgramGroupMatcher.match(List.of(new RevieweeGroupInput(g.id(),g.name(),null,ItemAssignmentMode.DESIGNATED,EvaluationMethod.ABSOLUTE,false,false,g.displayOrder(),g.conditions(),List.of(new ReviewerWeightPlanInput(1,Map.of(1,new BigDecimal("100")),BigDecimal.ZERO)))),json.participantAttributes(p.getAttributesJson())).isPresent()).map(DepartmentPerformanceGroupInput::grade).findFirst().orElseThrow(()->new ProgramRuleViolation("DEPARTMENT_GROUP","department performance group missing"));}
    private String departmentGroupId(ProgramConfiguration c,ProgramParticipant p){ParticipantAttributes a=json.participantAttributes(p.getAttributesJson());return c.departmentPerformanceGroups().stream().filter(g->g.conditions().stream().allMatch(condition->ProgramGroupMatcher.match(List.of(new RevieweeGroupInput(g.id(),g.name(),null,ItemAssignmentMode.DESIGNATED,EvaluationMethod.ABSOLUTE,false,false,g.displayOrder(),List.of(condition),List.of(new ReviewerWeightPlanInput(1,Map.of(1,new BigDecimal("100")),BigDecimal.ZERO)))),a).isPresent())).map(g->g.id().toString()).findFirst().orElse("UNMATCHED");}
    private int gradeDistance(ProgramConfiguration c,String from,String to){List<String> grades=c.scales().stream().filter(s->s.id().equals(c.calculation().resultScaleId())).findFirst().orElseThrow().levels().stream().map(ScaleLevelInput::code).toList();int a=grades.indexOf(from),b=grades.indexOf(to);if(a<0||b<0)throw new ProgramRuleViolation("GRADE_CODE","grade code is invalid");return Math.abs(a-b);}
    private static BigDecimal clamp(BigDecimal value){return value.max(BigDecimal.ZERO).min(new BigDecimal("100")).setScale(4,RoundingMode.HALF_UP);}
    private static final class RawCalculation{final ProgramParticipant participant;final List<ScoreContribution> contributions;final BigDecimal raw;BigDecimal normalized;BigDecimal adjusted;String grade;String formula;final List<String>warnings;RawCalculation(ProgramParticipant p,List<ScoreContribution>c,BigDecimal raw,BigDecimal normalized,BigDecimal adjusted,String grade,String formula,List<String>warnings){this.participant=p;this.contributions=c;this.raw=raw;this.normalized=normalized;this.adjusted=adjusted;this.grade=grade;this.formula=formula;this.warnings=warnings;}}
}
