package com.easyperformance.program;

import com.easyperformance.program.ProgramDtos.*;
import com.easyperformance.program.ProgramTypes.*;
import com.easyperformance.readmodel.entity.*;
import com.easyperformance.readmodel.repository.*;
import com.easyperformance.workflow.ActorAccess.Actor;
import com.easyware.platform.error.ApiException;
import com.easyware.platform.spreadsheet.SimpleXlsx;
import org.springframework.data.domain.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.*;

@Service
public class ProgramRosterService {
 private static final List<String> PARTICIPANT_HEADERS=List.of("employeeId","employeeNo","name","assignmentId","orgUnitId","weightPercent","status","groupId");
 private static final List<String> REVIEWER_HEADERS=List.of("participantId","reviewerEmployeeId","role","round","weightPercent");
 private final EvaluationProgramRepository programs;private final ProgramParticipantRepository participants;private final ProgramReviewerAssignmentRepository reviewers;private final RmEmployeeRepository employees;private final RmAssignmentRepository assignments;private final RmOrgUnitRepository orgs;private final ProgramAccess access;private final ProgramJson json;private final ProgramAuditService audit;
 public ProgramRosterService(EvaluationProgramRepository programs,ProgramParticipantRepository participants,ProgramReviewerAssignmentRepository reviewers,RmEmployeeRepository employees,RmAssignmentRepository assignments,RmOrgUnitRepository orgs,ProgramAccess access,ProgramJson json,ProgramAuditService audit){this.programs=programs;this.participants=participants;this.reviewers=reviewers;this.employees=employees;this.assignments=assignments;this.orgs=orgs;this.access=access;this.json=json;this.audit=audit;}

 @Transactional public List<ParticipantResponse> generate(Actor actor,UUID programId,ParticipantGenerateRequest request){access.requireOperator(actor);EvaluationProgram program=requireMutable(actor,programId);List<RmEmployee> source=request.employeeIds()==null||request.employeeIds().isEmpty()?allActive(actor.tenantId()):request.employeeIds().stream().distinct().map(id->activeEmployee(actor.tenantId(),id)).toList();List<ParticipantResponse> out=new ArrayList<>();for(RmEmployee employee:source){RmAssignment assignment=effectiveAssignment(actor.tenantId(),employee.getId(),program.getAsOfDate()).orElse(null);out.add(upsert(actor,program,employee,assignment,employee.getOrgUnitId(),new BigDecimal("100")));validateEmployeeWeightAtMost(actor.tenantId(),programId,employee.getId());}audit.record(actor,programId,null,ProgramEventType.PARTICIPANT_CREATED,"participants generated",Map.of("count",out.size()));return out;}
 @Transactional public ParticipantResponse add(Actor actor,UUID programId,ParticipantAddRequest request){access.requireOperator(actor);EvaluationProgram program=requireMutable(actor,programId);RmEmployee employee=activeEmployee(actor.tenantId(),request.employeeId());RmAssignment assignment=request.assignmentId()==null?effectiveAssignment(actor.tenantId(),employee.getId(),program.getAsOfDate()).orElse(null):assignments.findAllByTenantIdAndEmployeeId(actor.tenantId(),employee.getId()).stream().filter(a->a.getId().equals(request.assignmentId())).findFirst().orElseThrow(()->new ApiException(ProgramErrorCode.PROGRAM_INVALID,Map.of("reason","ASSIGNMENT_NOT_FOUND")));UUID org=request.orgUnitId()!=null?request.orgUnitId():assignment==null?employee.getOrgUnitId():assignment.getOrgUnitId();BigDecimal weight=request.weightPercent()==null?new BigDecimal("100"):request.weightPercent();ParticipantResponse response=upsert(actor,program,employee,assignment,org,weight);validateEmployeeWeightAtMost(actor.tenantId(),programId,employee.getId());audit.record(actor,programId,response.id(),ProgramEventType.PARTICIPANT_CREATED,"participant added",Map.of());return response;}
 @Transactional(readOnly=true) public Page<ParticipantResponse> list(Actor actor,UUID programId,Pageable pageable){access.program(actor,programId);if(access.operator(actor))return participants.findAllByTenantIdAndProgramId(actor.tenantId(),programId,pageable).map(p->response(actor.tenantId(),p));List<ParticipantResponse> visible=participants.findAllByTenantIdAndProgramIdOrderByCreatedAtAsc(actor.tenantId(),programId).stream().filter(p->access.canReadParticipant(actor,p)).map(p->response(actor.tenantId(),p)).toList();int from=(int)Math.min(pageable.getOffset(),visible.size());int to=Math.min(from+pageable.getPageSize(),visible.size());return new PageImpl<>(visible.subList(from,to),pageable,visible.size());}
 @Transactional public ParticipantResponse change(Actor actor,UUID participantId,ParticipantChangeRequest request){access.requireOperator(actor);ProgramParticipant p=access.participant(actor,participantId);requireMutable(actor,p.getProgramId());if(request.groupId()!=null){ProgramConfiguration c=config(actor,p.getProgramId());RevieweeGroupInput g=c.groups().stream().filter(x->x.id().equals(request.groupId())).findFirst().orElseThrow(()->new ProgramRuleViolation("GROUP_NOT_FOUND","group does not exist"));p.setGroupId(g.id());p.setGroupName(g.name());}if(request.status()!=null){p.setStatus(request.status());p.setExclusionReason(request.status()==ParticipantStatus.ACTIVE?null:requiredReason(request.reason()));}if(request.weightPercent()!=null)p.setWeightPercent(request.weightPercent());participants.save(p);validateEmployeeWeightAtMost(actor.tenantId(),p.getProgramId(),p.getEmployeeId());audit.record(actor,p.getProgramId(),p.getId(),ProgramEventType.PARTICIPANT_CHANGED,request.reason()==null?"participant changed":request.reason(),Map.of("status",p.getStatus()));return response(actor.tenantId(),p);}
 @Transactional public List<ReviewerResponse> replaceReviewers(Actor actor,UUID participantId,ReviewerReplaceRequest request){return replaceReviewers(actor,participantId,request,ReviewerAssignmentOrigin.MANUAL);}
 private List<ReviewerResponse> replaceReviewers(Actor actor,UUID participantId,ReviewerReplaceRequest request,ReviewerAssignmentOrigin origin){access.requireOperator(actor);ProgramParticipant p=access.participant(actor,participantId);EvaluationProgram program=requireMutable(actor,p.getProgramId());List<ProgramReviewerAssignment> old=reviewers.findAllByTenantIdAndParticipantIdAndStatusNotOrderByRoleAscRoundAsc(actor.tenantId(),p.getId(),AssignmentStatus.REVOKED);old.forEach(r->{r.setStatus(AssignmentStatus.REVOKED);reviewers.save(r);});validateReviewerPlan(config(actor,program.getId()),p,request.reviewers());List<ReviewerResponse> out=new ArrayList<>();for(ReviewerInput input:request.reviewers()){RmEmployee e=activeEmployee(actor.tenantId(),input.employeeId());ProgramReviewerAssignment r=new ProgramReviewerAssignment();r.setTenantId(actor.tenantId());r.setProgramId(program.getId());r.setParticipantId(p.getId());r.setReviewerEmployeeId(e.getId());r.setRole(input.role());r.setRound(input.round());r.setWeightPercent(input.weightPercent()==null?BigDecimal.ZERO:input.weightPercent());r.setAssignmentOrigin(origin);r=reviewers.save(r);out.add(response(r,e.getName()));}audit.record(actor,p.getProgramId(),p.getId(),ProgramEventType.REVIEWERS_CHANGED,"reviewers replaced",Map.of("count",out.size(),"origin",origin));return out;}
 @Transactional(readOnly=true) public List<ReviewerResponse> reviewers(Actor actor,UUID participantId){ProgramParticipant p=access.participant(actor,participantId);ProgramConfiguration c=config(actor,p.getProgramId());return reviewers.findAllByTenantIdAndParticipantIdAndStatusNotOrderByRoleAscRoundAsc(actor.tenantId(),p.getId(),AssignmentStatus.REVOKED).stream().filter(r->access.operator(actor)||c.publication().showReviewerAllocation()||Objects.equals(r.getReviewerEmployeeId(),actor.employeeId())).map(r->response(r,employeeName(actor.tenantId(),r.getReviewerEmployeeId()))).toList();}
 @Transactional public BatchOperationResponse startStage(Actor actor,UUID programId,ProgramStage stage,StageBatchRequest request){access.requireOperator(actor);EvaluationProgram program=requireOpen(actor,programId);ProgramConfiguration c=json.configuration(program.getDefinitionJson());if(c.stages().stream().noneMatch(s->s.stage()==stage&&s.enabled()))throw new ApiException(ProgramErrorCode.PROGRAM_STAGE_INVALID,Map.of("stage",stage));Set<UUID> selected=request.participantIds()==null||request.participantIds().isEmpty()?null:new HashSet<>(request.participantIds());List<UUID> changed=new ArrayList<>();List<BatchExclusion> excluded=new ArrayList<>();for(ProgramParticipant p:participants.findAllByTenantIdAndProgramIdOrderByCreatedAtAsc(actor.tenantId(),programId)){if(p.getStatus()!=ParticipantStatus.ACTIVE||(selected!=null&&!selected.contains(p.getId())))continue;String blocker=stageBlocker(actor.tenantId(),c,p,stage);if(blocker!=null){excluded.add(new BatchExclusion(p.getId(),"PREVIOUS_STAGE_INCOMPLETE",blocker));continue;}p.setCurrentStage(stage);p.setStageStatus(ProgramStageStatus.IN_PROGRESS);p.setCurrentRound(stage==ProgramStage.REVIEW?1:0);participants.save(p);changed.add(p.getId());audit.record(actor,programId,p.getId(),ProgramEventType.STAGE_CHANGED,request.reason(),Map.of("stage",stage,"status","IN_PROGRESS"));}return new BatchOperationResponse(changed.size(),changed,excluded);}
 @Transactional public ParticipantResponse overrideStage(Actor actor,UUID participantId,StageExceptionRequest request){access.requireOperator(actor);ProgramParticipant p=access.participant(actor,participantId);requireOpen(actor,p.getProgramId());p.setCurrentStage(request.toStage());p.setStageStatus(request.toStatus());p.setCurrentRound(request.round());participants.save(p);audit.record(actor,p.getProgramId(),p.getId(),ProgramEventType.STAGE_CHANGED,request.reason(),Map.of("stage",request.toStage(),"status",request.toStatus(),"round",request.round()));return response(actor.tenantId(),p);}
 @Transactional(readOnly=true) public byte[] exportParticipants(Actor actor,UUID programId){access.requireOperator(actor);List<ParticipantResponse> rows=list(actor,programId,PageRequest.of(0,10000)).getContent();List<List<String>> table=new ArrayList<>();table.add(PARTICIPANT_HEADERS);rows.forEach(p->table.add(List.of(text(p.employee().employeeId()),text(p.employee().employeeNo()),text(p.employee().name()),text(p.employee().assignmentId()),text(p.employee().orgUnitId()),p.weightPercent().toPlainString(),p.status().name(),text(p.groupId()))));return SimpleXlsx.write("Participants",table);}
 @Transactional public List<ParticipantResponse> importParticipants(Actor actor,UUID programId,byte[] bytes){List<List<String>> rows=SimpleXlsx.read(bytes);requireHeaders(rows,PARTICIPANT_HEADERS);List<ParticipantResponse> out=new ArrayList<>();for(int i=1;i<rows.size();i++){List<String> row=rows.get(i);if(row.stream().allMatch(String::isBlank))continue;UUID employeeId=parseUuid(cell(row,0),"employeeId");UUID assignmentId=parseNullableUuid(cell(row,3));UUID orgId=parseNullableUuid(cell(row,4));BigDecimal weight=new BigDecimal(cell(row,5));out.add(add(actor,programId,new ParticipantAddRequest(employeeId,assignmentId,orgId,weight)));}return out;}
 @Transactional(readOnly=true) public byte[] exportReviewers(Actor actor,UUID programId){access.requireOperator(actor);List<List<String>> table=new ArrayList<>();table.add(REVIEWER_HEADERS);for(ProgramParticipant p:participants.findAllByTenantIdAndProgramIdOrderByCreatedAtAsc(actor.tenantId(),programId))for(ReviewerResponse r:reviewers(actor,p.getId()))table.add(List.of(p.getId().toString(),r.reviewerEmployeeId().toString(),r.role().name(),Integer.toString(r.round()),r.weightPercent().toPlainString()));return SimpleXlsx.write("Reviewers",table);}
 @Transactional public List<ReviewerResponse> importReviewers(Actor actor,UUID programId,byte[] bytes){access.requireOperator(actor);requireMutable(actor,programId);List<List<String>> rows=SimpleXlsx.read(bytes);requireHeaders(rows,REVIEWER_HEADERS);Map<UUID,List<ReviewerInput>> grouped=new LinkedHashMap<>();for(int i=1;i<rows.size();i++){List<String> row=rows.get(i);if(row.stream().allMatch(String::isBlank))continue;UUID participantId=parseUuid(cell(row,0),"participantId");ProgramParticipant participant=access.participant(actor,participantId);if(!participant.getProgramId().equals(programId))throw new ProgramRuleViolation("XLSX_PARTICIPANT","participant belongs to another program");ReviewerInput input=new ReviewerInput(parseUuid(cell(row,1),"reviewerEmployeeId"),parseEnum(ReviewerRole.class,cell(row,2),"role"),parseInt(cell(row,3),"round"),new BigDecimal(cell(row,4)));grouped.computeIfAbsent(participantId,k->new ArrayList<>()).add(input);}List<ReviewerResponse> out=new ArrayList<>();grouped.forEach((participantId,input)->out.addAll(replaceReviewers(actor,participantId,new ReviewerReplaceRequest(input),ReviewerAssignmentOrigin.XLSX)));return out;}

 ParticipantResponse response(UUID tenantId,ProgramParticipant p){return new ParticipantResponse(p.getId(),p.getProgramId(),jsonReadAttributes(p),p.getGroupId(),p.getGroupName(),p.getStatus(),p.getWeightPercent(),p.getCurrentStage(),p.getStageStatus(),p.getCurrentRound(),p.isResultPublished(),p.getExclusionReason(),p.getRowVersion(),p.getUpdatedAt());}
 private ParticipantResponse upsert(Actor actor,EvaluationProgram program,RmEmployee employee,RmAssignment assignment,UUID orgId,BigDecimal weight){String key=assignment==null?"HOME:"+String.valueOf(orgId):assignment.getId().toString();ProgramParticipant p=participants.findByTenantIdAndProgramIdAndEmployeeIdAndAssignmentKey(actor.tenantId(),program.getId(),employee.getId(),key).orElseGet(ProgramParticipant::new);p.setTenantId(actor.tenantId());p.setProgramId(program.getId());p.setEmployeeId(employee.getId());p.setAssignmentId(assignment==null?null:assignment.getId());p.setAssignmentKey(key);p.setOrgUnitId(orgId);ParticipantAttributes attrs=attributes(actor.tenantId(),employee,assignment,orgId);RevieweeGroupInput group=ProgramGroupMatcher.match(config(program).groups(),attrs).orElse(null);p.setGroupId(group==null?null:group.id());p.setGroupName(group==null?null:group.name());p.setAttributesJson(json.write(attrs));p.setStatus(ParticipantStatus.ACTIVE);p.setWeightPercent(weight);if(p.getCurrentStage()==null){p.setCurrentStage(firstStage(config(program)));p.setStageStatus(ProgramStageStatus.NOT_STARTED);}return response(actor.tenantId(),participants.save(p));}
 private String stageBlocker(UUID tenantId,ProgramConfiguration c,ProgramParticipant p,ProgramStage target){if(p.getGroupId()==null)return "reviewee group is unmatched";List<ProgramStage> stages=effectiveStages(c,p);int index=stages.indexOf(target);if(index<0)return "stage is not enabled for the participant group";if(employeeWeight(tenantId,p.getProgramId(),p.getEmployeeId()).compareTo(new BigDecimal("100"))!=0)return "active participant weights for the employee must total 100";ReviewerRole required=switch(target){case GOAL->c.goalMode()==GoalMode.AGREEMENT?ReviewerRole.AGREEMENT_REVIEWER:null;case INTERMEDIATE->ReviewerRole.CHECKER;case REVIEW->ReviewerRole.REVIEWER;case CALIBRATION->ReviewerRole.ADJUSTER;case FEEDBACK->ReviewerRole.FINAL_FEEDBACK;default->null;};if(required!=null){int round=required==ReviewerRole.REVIEWER?1:0;if(reviewers.findByTenantIdAndParticipantIdAndRoleAndRoundAndStatusNot(tenantId,p.getId(),required,round,AssignmentStatus.REVOKED).isEmpty())return required+" is unassigned";}if(index==0)return null;ProgramStage previous=stages.get(index-1);if(p.getCurrentStage()==previous&&p.getStageStatus()==ProgramStageStatus.COMPLETED)return null;if(p.getCurrentStage()==target)return null;return previous+" is incomplete";}
 private List<ProgramStage> effectiveStages(ProgramConfiguration c,ProgramParticipant p){RevieweeGroupInput group=c.groups().stream().filter(g->g.id().equals(p.getGroupId())).findFirst().orElse(null);return c.stages().stream().filter(StageDefinitionInput::enabled).map(StageDefinitionInput::stage).filter(stage->stage!=ProgramStage.INTERMEDIATE||(group!=null&&group.intermediateEnabled())).filter(stage->stage!=ProgramStage.SELF_REVIEW||(group!=null&&group.selfReviewEnabled())).toList();}
 private void validateReviewerPlan(ProgramConfiguration c,ProgramParticipant p,List<ReviewerInput> inputs){Set<String> unique=new HashSet<>(),slots=new HashSet<>();for(ReviewerInput i:inputs){String k=i.role()+":"+i.round()+":"+i.employeeId();if(!unique.add(k)||!slots.add(i.role()+":"+i.round()))throw new ProgramRuleViolation("DUPLICATE_REVIEWER","each reviewer role and round has exactly one assignee");if(i.role()==ReviewerRole.REVIEWER&&(i.round()<1||i.round()>3))throw new ProgramRuleViolation("REVIEWER_ROUND","review round must be 1..3");if(i.role()!=ReviewerRole.REVIEWER&&i.round()!=0)throw new ProgramRuleViolation("NON_REVIEWER_ROUND","non-review roles use round 0");if(i.role()!=ReviewerRole.REVIEWER&&i.weightPercent()!=null&&i.weightPercent().compareTo(BigDecimal.ZERO)!=0)throw new ProgramRuleViolation("NON_REVIEWER_WEIGHT","non-review roles use zero weight");}List<ReviewerInput> scored=inputs.stream().filter(i->i.role()==ReviewerRole.REVIEWER).sorted(Comparator.comparingInt(ReviewerInput::round)).toList();if(!scored.isEmpty()){for(int index=0;index<scored.size();index++)if(scored.get(index).round()!=index+1)throw new ProgramRuleViolation("REVIEWER_ROUND","review rounds must be contiguous from 1");RevieweeGroupInput g=c.groups().stream().filter(x->x.id().equals(p.getGroupId())).findFirst().orElseThrow(()->new ProgramRuleViolation("GROUP_NOT_FOUND","participant group missing"));ReviewerWeightPlanInput plan=g.reviewerWeightPlans().stream().filter(x->x.actualReviewerCount()==scored.size()).findFirst().orElseThrow(()->new ProgramRuleViolation("WEIGHT_PLAN_MISSING","reviewer count weight plan missing"));for(ReviewerInput i:scored)if(i.weightPercent()==null||i.weightPercent().compareTo(plan.reviewerWeights().get(i.round()))!=0)throw new ProgramRuleViolation("REVIEWER_WEIGHT_MISMATCH","reviewer weights must match group plan");}}
 private ProgramConfiguration config(Actor a,UUID id){return config(access.program(a,id));}private ProgramConfiguration config(EvaluationProgram p){return json.configuration(p.getDefinitionJson());}
 private EvaluationProgram requireMutable(Actor a,UUID id){EvaluationProgram p=programs.findLocked(id,a.tenantId()).orElseThrow(()->new ApiException(ProgramErrorCode.PROGRAM_NOT_FOUND));if(p.getStatus()==ProgramStatus.FINALIZED||p.getStatus()==ProgramStatus.CANCELLED)throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED);return p;}private EvaluationProgram requireOpen(Actor a,UUID id){EvaluationProgram p=programs.findLocked(id,a.tenantId()).orElseThrow(()->new ApiException(ProgramErrorCode.PROGRAM_NOT_FOUND));if(p.getStatus()!=ProgramStatus.OPEN)throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED,Map.of("required","OPEN"));return p;}
 private RmEmployee activeEmployee(UUID tenant,UUID id){return employees.findByIdAndTenantId(id,tenant).filter(e->"ACTIVE".equalsIgnoreCase(e.getStatus())).orElseThrow(()->new ApiException(ProgramErrorCode.PROGRAM_INVALID,Map.of("employeeId",id)));}private List<RmEmployee> allActive(UUID tenant){List<RmEmployee> out=new ArrayList<>();for(int page=0;;page++){Page<RmEmployee> slice=employees.searchActive(tenant,"",PageRequest.of(page,200));out.addAll(slice.getContent());if(!slice.hasNext())break;}return out;}
 private Optional<RmAssignment> effectiveAssignment(UUID tenant,UUID employee,LocalDate date){return assignments.findAllByTenantIdAndEmployeeId(tenant,employee).stream().filter(a->(a.getEffectiveFrom()==null||!a.getEffectiveFrom().isAfter(date))&&(a.getEffectiveTo()==null||!a.getEffectiveTo().isBefore(date))).max(Comparator.comparing(a->a.getEffectiveFrom()==null?LocalDate.MIN:a.getEffectiveFrom()));}
 private ParticipantAttributes attributes(UUID tenant,RmEmployee e,RmAssignment a,UUID org){String orgName=org==null?null:orgs.findByIdAndTenantId(org,tenant).map(RmOrgUnit::getName).orElse(null);return new ParticipantAttributes(e.getId(),e.getEmployeeNo(),e.getName(),a==null?null:a.getId(),org,orgName,a==null?null:a.getPositionCode(),a==null?null:a.getGradeCode(),a==null?null:a.getJobCode(),e.getEmploymentType());}
 private ParticipantAttributes jsonReadAttributes(ProgramParticipant p){return json.participantAttributes(p.getAttributesJson());}
 private ProgramStage firstStage(ProgramConfiguration c){return c.stages().stream().filter(StageDefinitionInput::enabled).map(StageDefinitionInput::stage).findFirst().orElseThrow(()->new ProgramRuleViolation("NO_STAGE","at least one stage required"));}
 private ReviewerResponse response(ProgramReviewerAssignment r,String name){return new ReviewerResponse(r.getId(),r.getParticipantId(),r.getReviewerEmployeeId(),name,r.getRole(),r.getRound(),r.getWeightPercent(),r.getStatus());}private String employeeName(UUID tenant,UUID id){return employees.findByIdAndTenantId(id,tenant).map(RmEmployee::getName).orElse("Unknown");}
 private void validateEmployeeWeightAtMost(UUID tenant,UUID program,UUID employee){if(employeeWeight(tenant,program,employee).compareTo(new BigDecimal("100"))>0)throw new ProgramRuleViolation("PARTICIPANT_WEIGHT_SUM","active participant weights for an employee cannot exceed 100");}
 private BigDecimal employeeWeight(UUID tenant,UUID program,UUID employee){return participants.findAllByTenantIdAndProgramIdOrderByCreatedAtAsc(tenant,program).stream().filter(p->p.getEmployeeId().equals(employee)&&p.getStatus()==ParticipantStatus.ACTIVE).map(ProgramParticipant::getWeightPercent).reduce(BigDecimal.ZERO,BigDecimal::add);}
 private static String requiredReason(String reason){if(reason==null||reason.isBlank())throw new ProgramRuleViolation("REASON_REQUIRED","reason is required");return reason;}private static void requireHeaders(List<List<String>> rows,List<String> expected){if(rows.isEmpty()||!rows.getFirst().equals(expected))throw new ProgramRuleViolation("XLSX_HEADERS","xlsx headers do not match template");}private static String cell(List<String> row,int i){return i<row.size()?row.get(i).trim():"";}private static UUID parseUuid(String v,String field){try{return UUID.fromString(v);}catch(Exception e){throw new ProgramRuleViolation("XLSX_VALUE","invalid "+field);}}private static UUID parseNullableUuid(String v){return v==null||v.isBlank()?null:parseUuid(v,"uuid");}private static String text(Object v){return v==null?"":v.toString();}
 private static int parseInt(String v,String field){try{return Integer.parseInt(v);}catch(Exception e){throw new ProgramRuleViolation("XLSX_VALUE","invalid "+field);}}private static <E extends Enum<E>> E parseEnum(Class<E> type,String value,String field){try{return Enum.valueOf(type,value);}catch(Exception e){throw new ProgramRuleViolation("XLSX_VALUE","invalid "+field);}}
}
