package com.easyperformance.program;

import com.easyperformance.program.ProgramDtos.*;
import com.easyperformance.program.ProgramTypes.*;
import com.easyperformance.workflow.ActorAccess.Actor;
import com.easyware.platform.error.ApiException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;
import java.util.*;

@Service
public class ProgramLifecycleService {
 private final EvaluationProgramRepository programs;private final ProgramParticipantRepository participants;private final ProgramCalculationRepository calculations;private final ProgramAdjustmentRepository adjustments;private final ProgramFeedbackRepository feedback;private final ProgramAccess access;private final ProgramJson json;private final ProgramAuditService audit;private final EvaluationProgramService programService;
 public ProgramLifecycleService(EvaluationProgramRepository programs,ProgramParticipantRepository participants,ProgramCalculationRepository calculations,ProgramAdjustmentRepository adjustments,ProgramFeedbackRepository feedback,ProgramAccess access,ProgramJson json,ProgramAuditService audit,EvaluationProgramService programService){this.programs=programs;this.participants=participants;this.calculations=calculations;this.adjustments=adjustments;this.feedback=feedback;this.access=access;this.json=json;this.audit=audit;this.programService=programService;}
 @Transactional public ProgramResponse finalizeProgram(Actor actor,UUID id,FinalizeRequest request){EvaluationProgram p=access.lockedProgram(actor,id);if(p.getStatus()!=ProgramStatus.OPEN)throw new ApiException(ProgramErrorCode.PROGRAM_LOCKED);ProgramConfiguration c=json.configuration(p.getDefinitionJson());List<Map<String,Object>> blockers=new ArrayList<>();for(ProgramParticipant participant:participants.findAllByTenantIdAndProgramIdOrderByCreatedAtAsc(actor.tenantId(),id)){if(participant.getStatus()!=ParticipantStatus.ACTIVE)continue;ProgramStage lastStage=lastStage(c,participant);if(participant.getCurrentStage()!=lastStage||(participant.getStageStatus()!=ProgramStageStatus.COMPLETED&&participant.getStageStatus()!=ProgramStageStatus.SKIPPED))blockers.add(block(participant,"LAST_STAGE_INCOMPLETE"));ProgramCalculation calc=calculations.findAllByTenantIdAndParticipantIdOrderByRevisionDesc(actor.tenantId(),participant.getId()).stream().filter(x->x.getStatus()==CalculationStatus.FINAL).findFirst().orElse(null);if(calc==null)blockers.add(block(participant,"CALCULATION_MISSING"));else if(p.getUpdatedAt()!=null&&!calc.getCalculatedAt().isAfter(p.getUpdatedAt()))blockers.add(block(participant,"CALCULATION_STALE"));if(enabled(c,ProgramStage.CALIBRATION)&&(calc==null||adjustments.findFirstByTenantIdAndParticipantIdOrderByRevisionDesc(actor.tenantId(),participant.getId()).filter(a->a.getStatus()==AdjustmentStatus.COMPLETED&&a.getCalculationId().equals(calc.getId())).isEmpty()))blockers.add(block(participant,"ADJUSTMENT_INCOMPLETE_OR_STALE"));if(c.publication().feedbackEnabled()){ProgramFeedback f=feedback.findByTenantIdAndParticipantId(actor.tenantId(),participant.getId()).orElse(null);if(f==null||(f.getStatus()!=FeedbackStatus.AGREED&&f.getStatus()!=FeedbackStatus.RESOLVED))blockers.add(block(participant,"FEEDBACK_INCOMPLETE"));}}if(!blockers.isEmpty())throw new ApiException(ProgramErrorCode.PROGRAM_INCOMPLETE,Map.of("blockers",blockers));p.setStatus(ProgramStatus.FINALIZED);p.setFinalizedAt(Instant.now());programs.save(p);audit.record(actor,id,null,ProgramEventType.FINALIZED,request.reason(),Map.of());return programService.response(p);}
 @Transactional public ProgramResponse cancelFinalization(Actor actor,UUID id,FinalizationCancelRequest request){EvaluationProgram p=access.lockedProgram(actor,id);if(p.getStatus()!=ProgramStatus.FINALIZED)throw new ApiException(ProgramErrorCode.PROGRAM_STAGE_INVALID);for(ProgramParticipant participant:participants.findAllByTenantIdAndProgramIdOrderByCreatedAtAsc(actor.tenantId(),id)){participant.setResultPublished(false);participants.save(participant);feedback.findByTenantIdAndParticipantId(actor.tenantId(),participant.getId()).filter(f->f.getStatus()!=FeedbackStatus.DRAFT).ifPresent(f->{audit.record(actor,id,participant.getId(),ProgramEventType.FEEDBACK_INVALIDATED,request.reason(),feedbackSnapshot(f));f.setStatus(FeedbackStatus.DRAFT);f.setComment(null);f.setAppealReason(null);f.setResolution(null);f.setResolutionComment(null);f.setDeliveredAt(null);f.setResolvedAt(null);feedback.save(f);});}p.setStatus(ProgramStatus.OPEN);p.setFinalizedAt(null);programs.save(p);audit.record(actor,id,null,ProgramEventType.FINALIZATION_CANCELLED,request.reason(),Map.of("publishedResultsWithdrawn",true,"calculationsPreservedAsHistory",true,"feedbackSnapshotsPreservedInAudit",true));return programService.response(p);}
 @Transactional public BatchOperationResponse publish(Actor actor,UUID id,PublishRequest request){access.requireOperator(actor);EvaluationProgram p=programs.findLocked(id,actor.tenantId()).orElseThrow(()->new ApiException(ProgramErrorCode.PROGRAM_NOT_FOUND));if(p.getStatus()!=ProgramStatus.FINALIZED)throw new ApiException(ProgramErrorCode.PROGRAM_STAGE_INVALID);List<UUID> changed=new ArrayList<>();List<BatchExclusion> excluded=new ArrayList<>();for(UUID participantId:new LinkedHashSet<>(request.participantIds())){ProgramParticipant participant=participants.findByIdAndTenantId(participantId,actor.tenantId()).orElse(null);if(participant==null||!participant.getProgramId().equals(id)||participant.getStatus()!=ParticipantStatus.ACTIVE){excluded.add(new BatchExclusion(participantId,"NOT_ELIGIBLE","participant is not an active member of the program"));continue;}if(calculations.findAllByTenantIdAndParticipantIdOrderByRevisionDesc(actor.tenantId(),participantId).stream().noneMatch(x->x.getStatus()==CalculationStatus.FINAL)){excluded.add(new BatchExclusion(participantId,"RESULT_MISSING","final result is missing"));continue;}participant.setResultPublished(true);participants.save(participant);changed.add(participantId);audit.record(actor,id,participantId,ProgramEventType.RESULT_PUBLISHED,"result published",Map.of());}return new BatchOperationResponse(changed.size(),changed,excluded);}
 @Transactional(readOnly=true)public ProgramDashboardResponse dashboard(Actor actor,UUID id){access.program(actor,id);List<ProgramParticipant> rows=participants.findAllByTenantIdAndProgramIdOrderByCreatedAtAsc(actor.tenantId(),id).stream().filter(p->access.canReadParticipant(actor,p)).toList();Map<ProgramStage,Long> ready=count(rows,ProgramStageStatus.READY),inProgress=count(rows,ProgramStageStatus.IN_PROGRESS),completed=count(rows,ProgramStageStatus.COMPLETED),blocked=count(rows,ProgramStageStatus.BLOCKED);return new ProgramDashboardResponse(id,rows.stream().filter(p->p.getStatus()==ParticipantStatus.ACTIVE).count(),rows.stream().filter(p->p.getStatus()==ParticipantStatus.EXCLUDED).count(),ready,inProgress,completed,blocked);}
 private static Map<ProgramStage,Long> count(List<ProgramParticipant> rows,ProgramStageStatus status){Map<ProgramStage,Long> result=new EnumMap<>(ProgramStage.class);for(ProgramParticipant p:rows)if(p.getCurrentStage()!=null&&p.getStageStatus()==status)result.merge(p.getCurrentStage(),1L,Long::sum);return result;}
 private static ProgramStage lastStage(ProgramConfiguration c,ProgramParticipant p){RevieweeGroupInput group=c.groups().stream().filter(g->g.id().equals(p.getGroupId())).findFirst().orElse(null);return c.stages().stream().filter(StageDefinitionInput::enabled).map(StageDefinitionInput::stage).filter(stage->stage!=ProgramStage.INTERMEDIATE||(group!=null&&group.intermediateEnabled())).filter(stage->stage!=ProgramStage.SELF_REVIEW||(group!=null&&group.selfReviewEnabled())).reduce((a,b)->b).orElseThrow(()->new ProgramRuleViolation("NO_STAGE","at least one stage is required"));}
 private static Map<String,Object> feedbackSnapshot(ProgramFeedback f){Map<String,Object> value=new LinkedHashMap<>();value.put("feedbackId",f.getId());value.put("status",f.getStatus());value.put("writerEmployeeId",f.getWriterEmployeeId());value.put("comment",f.getComment());value.put("appealReason",f.getAppealReason());value.put("resolution",f.getResolution());value.put("resolutionComment",f.getResolutionComment());value.put("deliveredAt",f.getDeliveredAt());value.put("resolvedAt",f.getResolvedAt());return value;}
 private static boolean enabled(ProgramConfiguration c,ProgramStage s){return c.stages().stream().anyMatch(x->x.stage()==s&&x.enabled());}private static Map<String,Object> block(ProgramParticipant p,String reason){return Map.of("participantId",p.getId(),"reason",reason);}
}
